### PR TITLE
Improve testability + small code changes of AppSideBarTabs

### PR DESCRIPTION
**Pull request by LiquidITGuy**
Hi,

I added unit tests on already tested component to familiarize myself with the code.
I also fix some warning on the passing tests of the current code (stub of console does not work as expected)

During this phase I found a bug with the key listener.
According to the documentation, we can use the kebab-case standard even if it’s not a defined shortcut.
https://vuejs.org/v2/guide/events.html#Key-Modifiers
But it doesn’t seem to work on every system.
Other events seems to trigger the listeners ‘keydown.page-up’ and ‘page down’.
You can try it with the written tests.
According to Vue-test-utils the key to trigger it in tests are ‘pageup’ and ‘pagedown’.
https://vue-test-utils.vuejs.org/guides/dom-events.html

May it be an issue in Vuejs listener process on some engines?
For now I fixed it with the keyboard code.
After writing those tests, I make some minor change into the code to make it easier to reuse.

I would be happy to have feedback to know if pull requests like this one can be helpful or not or to view it merged :).
Capture d’écran 2020-10-23 à 22 27 38
Capture d’écran 2020-10-23 à 22 27 46

### CODE REVIEW

**Comment by LiquidITGuy** [comment]
any one ?

**Comment by LiquidITGuy** [comment]
May I ask for some feedback ?
(If this kind of pr can help to improve testability or fiability of the front, I would be happy to create more pull request during my free time :) )

**Comment by skjnldsv** [comment]
Hey!!
I'm so sorry we missed it! :see_no_evil: 
Thank you so much for opening this pr, we'll have a look at it :eye::lips::eye:

**Comment by skjnldsv** [comment]
Could you rebase to master?

**Comment by LiquidITGuy** [comment]
> Could you rebase to master?

Sure I will do it tomorrow :)

**Comment by LiquidITGuy** [comment]
@skjnldsv done :)

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Very nice!!

**Review by ChristophWurst — APPROVED** [review]
:rocket:

**Comment by skjnldsv** [comment]
:tada: :tada: :tada: :tada:

**Comment by skjnldsv** [comment]
Thank you so much @LiquidITGuy 
Welcome!

**Pull request merged**
