### PR TITLE
Implement switch mode to CheckboxRadioSwitch

### LINKED ISSUE #1710: Implement switch component
All accross Nextcloud we're using checkboxes as toggles. This is not an ideal UI/UX practice and we should use a switch in those cases.

More info: https://uxmovement.com/buttons/when-to-use-a-switch-or-checkbox/

For example, this should be a toggle: 

https://user-images.githubusercontent.com/26852655/107814937-97763700-6d6a-11eb-9eef-c05835739bee.mp4

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #1710 

image

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]
Very nice

**Comment by skjnldsv** [comment]
image

**Review by ma12-co — APPROVED** [review]
Very nice!
The only feedback I have is that I find it a bit small, could we increase the size of it to match the height of the checkbox and have the width scale proportionally?

**Comment by skjnldsv** [comment]
> The only feedback I have is that I find the switch a bit small, could we increase the size of it to match the height of the checkbox and have the width scale proportionally?

Can be easily done here: https://github.com/nextcloud/nextcloud-vue/blob/866c3c030a4a7ebc8203f3e2597fcf12bfe81be7/src/components/CheckboxRadioSwitch/CheckboxRadioSwitch.vue#L268
Ask Jan about it :)

**Pull request merged**
