### PR TITLE
Add Nc prefix to all components

### LINKED ISSUE #2643: Rename Vue components to multi word components
According to https://eslint.vuejs.org/rules/multi-word-component-names.html the component names should not be named with a single word to avoid conflicts with current or future html tags.

An example is the Button component, which could cause conflicts with the html tag button. 

Affected components: 
* Actions
* Avatar
* Breadcrump
* Breadcrumps
* Button
* Content
* Highlight
* Modal
* Popover

Maybe the vue3 migration could be a good point to optimize this.

### PR DESCRIPTION
**Pull request by raimund-schluessler**
This adds the `Nc` prefix to all component names to be in line with eslint and consistent for all components.

This was not a fun thing to do, and won't be when migrating apps :see_no_evil:

Closes #2643, supersedes #3050

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]
Thanks a lot

**Review by nickvergessen — APPROVED** [review]
There's an elephant in my room

**Comment by skjnldsv** [comment]
Conflicts!

**Comment by nickvergessen** [comment]
We should stop merging stuff until this is in.

Conflict caused by a one liner
https://github.com/nextcloud/nextcloud-vue/pull/3059

**Review by vinicius73 — APPROVED** [review]

**Comment by raimund-schluessler** [comment]
Rebased.

**Pull request merged**
