### PR TITLE
Revert "AppSidebar: fix tab validation: tabs are optional"

### PR DESCRIPTION
**Pull request by skjnldsv**
Reverts nextcloud/nextcloud-vue#445

### CODE REVIEW

**Comment by skjnldsv** [comment]
Hey @korelstar 
There was an issue with your fix. If you're not using the appsidebarTab component, then the tabs are always empty, so using reduce on an empty array will never check anything :)

**Comment by skjnldsv** [comment]
Could you open again a fix so we can have a better look at it? :)
You're awesome! Tanks! :hugs:

**Comment by korelstar** [comment]
What exactly didn't work and why should it work? It is intended, that non-AppSidebarTab's are not shown as tabs but as normal content.

**Comment by skjnldsv** [comment]
Issue is that you can use other components as tabs, as long as you're providing the appropriate icon and name and id. Now if you check the tab component only, it will forbid it :)

(sorry about the late answer)

You can see the current pending pr that broke after your patch : https://github.com/nextcloud/server/pull/15719
:wink:

**Comment by korelstar** [comment]
Okay, then I suggest to make the check as you wrote: a children is treated as tab if it has icon, id and name, otherwise it is treated as non-tab content. However, then your detailed warnings are not possible anymore.

The only other solution I see is to revert #420, since that enforces tabs, which is not intended.

**Comment by skjnldsv** [comment]
I'll adapt your pr and 420 :)
Thanks for the help @korelstar ! :hugs: 

PS: are you coming at the conference this year? :rocket:

**Comment by korelstar** [comment]
What about using different template slots for tabs and for non-tab-content? Then, it would be easy to check if and warn if not only one of them is used. I think that would provide a much clearer distinction between these two use cases. Unfortunately, this would be a breaking change (slot has to be used for tabs).

What do you think, @skjnldsv ?

**Comment by korelstar** [comment]
> I'll adapt your pr and 420 :)

@skjnldsv Any news on this? There is still an error message when using no tabs in AppSidebar. Are you fine with slitting tabs and non-tab content in two different template slots? Then I could provide a PR.

**Pull request merged**
