### PR TITLE
Implement cron job to synchronise server styling

### LINKED ISSUE #3325: Cypress tests broken due external changes to server repo
Probably due to #3139 the visual regression tests now get the server CSS live from the server repo. This randomly breaks the visual regression tests here.

Imho this is not a good idea, since  then unrelated changes randomly make the cypress tests fails and can't get merged, see e.g. #3323. Furthermore, we then don't know if it was a change here, or in the server that makes the tests fail.

@skjnldsv @CarlSchwan @vinicius73

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #3325 

Every night, we'll have a server sync and a PR will be created if any changes

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
That sounds good. But I think styleguide/assets/additional.css needs to be adjusted as well.

**Comment by skjnldsv** [comment]
> That sounds good. But I think styleguide/assets/additional.css needs to be adjusted as well.

Done, completely forgot to change it :see_no_evil:

**Comment by skjnldsv** [comment]
I purposefully shipped outdated css in this PR, so we can fire the cron job right after merging and see if everything works fine :)

**Review by szaimen — APPROVED** [review]
🐘

**Comment by skjnldsv** [comment]
Fixed imports.

**Comment by skjnldsv** [comment]
Ok, let's merge and check the workflow

**Pull request merged**
