### PR TITLE
Add undo trailing icon

### PR DESCRIPTION
**Pull request by Pytal**
Add an `"undo"` icon in addition to the `"close"` and `"arrowRight"` icons

### CODE REVIEW

**Comment by Pytal** [comment]
For some reason this affects the NcAppSidebar cypress tests

**Comment by artonge** [comment]
Can we mark `trailingButtonIcon` as deprecated?

**Comment by raimund-schluessler** [comment]
> For some reason this affects the NcAppSidebar cypress tests

No idea why, but the color of the favorite icon changed.
Before:
NcAppSidebar vue-subtitle_null-starred_true-compact_true-header_image-secondary_button-editable_false-base

After:
NcAppSidebar vue-subtitle_null-starred_true-compact_true-header_image-secondary_button-editable_false-actual

**Comment by raimund-schluessler** [comment]
Could it be that a change in server now makes the cypress tests fail due to https://github.com/nextcloud/nextcloud-vue/pull/3139? The cypress tests for a PR that got merged yesterday without issues (https://github.com/nextcloud/nextcloud-vue/actions/runs/3159764008/jobs/5152100405) now also fails. I think it is less than ideal that external changes break the tests for this repository without interaction. There is no way of catching or debugging this.

@skjnldsv @marcoambrosini

**Comment by raimund-schluessler** [comment]
I created a separate issue for this https://github.com/nextcloud/nextcloud-vue/issues/3325

**Comment by marcoambrosini** [comment]
@Pytal We deliberately limited the functionality there to control the design a bit more. What trailing icon do you need there?

**Comment by Pytal** [comment]
> Can we mark `trailingButtonIcon` as deprecated so we can remove it in a few major bump?

Did not mention deprecating anything?

**Comment by Pytal** [comment]
> @Pytal We deliberately limited the functionality there to control the design a bit more. What trailing icon do you need there?

Would need the `undo-variant` icon from https://materialdesignicons.com, and had thought of adding another string `undo` to use this icon but thought that allowing any icon would prevent having to update the component each time a new icon is needed in the future

**Comment by Pytal** [comment]
Should we add the `undo-variant` icon case or allow any custom icon @marcoambrosini?

**Comment by marcoambrosini** [comment]
Yes I think we should add only `undo-variant` and proceed slowly keep things under control. cc @jancborchardt @nimishavijay

**Comment by Pytal** [comment]
Review-ready

**Review by szaimen — APPROVED** [review]

**Review by marcoambrosini — APPROVED** [review]

**Pull request merged**
