### PR TITLE
Update action hover feedback

### PR DESCRIPTION
**Pull request by ma12-co**
As discussed with @jancborchardt 

Peek 2021-02-02 14-50

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

**Review by nickvergessen — COMMENTED** [review]
Looks good in talk

**Comment by nickvergessen** [comment]
In the second you click it looks like all feedback is missing?

**Comment by ma12-co** [comment]
> In the second you click it looks like all feedback is missing?

The behavior is exactly the same as now, I'm only changing appearance of the feedback

**Review by nickvergessen — APPROVED** [review]

**Review by GretaD — APPROVED** [review]
:+1:

**Pull request merged**
