### PR TITLE
Fix contrast of next/prev modal buttons

### PR DESCRIPTION
**Pull request by Pytal**
Fix https://github.com/nextcloud/nextcloud-vue/issues/2954

Before | After
--- | ---
image | image
image | image

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: nice

**Review by artonge — APPROVED** [review]

**Review by artonge — CHANGES_REQUESTED** [review]

**Comment by Pytal** [comment]
> Is it normal that the button is more than half the height of the screen ? Looks weird no ?

Adjusted

**Review by artonge — APPROVED** [review]

**Review by szaimen — CHANGES_REQUESTED** [review]
Did someone tested these adjustments with the viewer app on mobile? Will ths next/prev button overlap the video controls again?

See https://github.com/nextcloud/nextcloud-vue/pull/2099

**Comment by skjnldsv** [comment]
Considering the desig nchange and click area, I'd like an approval by @jancborchardt before we merge.

If the click area is so tiny, it will reduce the Viewer usability tremendously.
I'd be up to use proper margins to make sure the visual looks good, but the clickable prev/next area is still taking a fair amount of the page height

**Comment by Pytal** [comment]
> Did someone tested these adjustments with the viewer app on mobile? Will ths next/prev button overlap the video controls again?
> 
> See #2099

Doesn't seem to overlap
image

**Comment by Pytal** [comment]
We can restore the height to `35vw` if that's good with you @jancborchardt @artonge?

**Comment by jancborchardt** [comment]
I'm fine with either height. @skjnldsv good point with the taller tappable area, but could we achieve that without it looking so tall visually as well?

**Comment by Pytal** [comment]
Restored height to `35vw` and updated screenshots

> I'm fine with either height. @skjnldsv good point with the taller tappable area, but could we achieve that without it looking so tall visually as well?

Making part of the tap area visible and the rest invisible does not seem viable so we can just make it all visible as before

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
