### PR TITLE
l10n: Separate words

### PR DESCRIPTION
**Pull request by Valdnet**

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Whoopsie. It might take a while until I retrain my brain for this. Same as *trash bin* instead of *trashbin* :see_no_evil:

**Review by Pytal — COMMENTED** [review]
Might want to address this at https://github.com/nextcloud/nextcloud-vue/blob/31513b4a27ae5ddd81eb1b87376d7d67bdc8344f/src/components/DatetimePicker/DatetimePicker.vue#L74-L77 and https://github.com/nextcloud/nextcloud-vue/blob/31513b4a27ae5ddd81eb1b87376d7d67bdc8344f/src/components/DatetimePicker/DatetimePicker.vue#L206-L208 :)

**Comment by Valdnet** [comment]
@Pytal Changed in the descriptions for the developer.

@ChristophWurst Developers have a bigger problem with typing correctness because they remember words from functions, which is very wrong for remembering and associating for correct typing 😉.

**Review by Pytal — APPROVED** [review]

**Comment by Pytal** [comment]
CI suggests 👇 :)
```bash
npm run l10n:extract
```

**Comment by Valdnet** [comment]
> CI suggests 👇 :)
> 
> npm run l10n:extract

@Pytal I don't think I can do it from the GitHub position.

**Comment by Pytal** [comment]
> @Pytal I don't think I can do it from the GitHub position.

You may try running it on your machine :)

**Comment by Valdnet** [comment]
> You may try running it on your machine :)

@Pytal I don't have any compiler on my machine. I make a lot of changes via GitHub. Could you do this on yours?

**Comment by Pytal** [comment]
> @Pytal I don't have any compiler on my machine. I make a lot of changes via GitHub. Could you do this on yours?

Done :)

**Comment by Valdnet** [comment]
@Pytal Thank you very much 😉.

**Pull request merged**
