### PR TITLE
Show icon instead of status if not in do not disturbe mode

### PR DESCRIPTION
**Pull request by juliushaertl**
image

How it looks in talk ([note that the duplicate icon needs a fixing there](https://github.com/nextcloud/spreed/pull/4253)):
image

I played around a bit with a circled white background but this might look odd depending on the emoji. 

@jancborchardt Feel free to play around with the styles if needed

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice work! :) 

@karlitschek what do you think? My only concern is that we now don’t show the online/away status for people with a custom status, but still for others – but that might just be fine.

**Comment by nickvergessen** [comment]
Talk fix is in https://github.com/nextcloud/spreed/pull/4253

**Comment by Ivansss** [comment]
I don't want to sound wrong but in my opinion this adds more confusion between "user status" and "status message".
I think this wording change https://github.com/nextcloud/server/pull/23113 was good to separate these two concepts.
But with this PR I think we are again mixing both concepts which could lead to a confusion.
I was not involved in the discussion so maybe I'm missing something. This is just a personal opinion :)

**Comment by karlitschek** [comment]
The user set status is more important then 'online'. Again online doesn't tell me anything beside that someone used Nextcloud in the last 10min.

**Review by rullzer — APPROVED** [review]

**Comment by karlitschek** [comment]
I don't get the special logic with 'do not disturb' here

**Comment by jancborchardt** [comment]
> I don't get the special logic with 'do not disturb' here

The idea is that when people set "do not disturb" cause they are in a meeting or something else, that is more important to signify than the emoji of the general status.

We can also cut that at just overwrite "Do not disturb" as well – your call.

**Comment by jancborchardt** [comment]
Guess needs a new release?

**Pull request merged**
