### PR TITLE
Add modal sizes

### PR DESCRIPTION
**Pull request by skjnldsv**
| big | medium | normal |
|:---------:|:---------:|:------:|
|dev skjnldsv com_apps_vueexample_|dev skjnldsv com_apps_vueexample_ (1)|dev skjnldsv com_apps_vueexample_ (2)|

I'm not convinced on the positions of the navigation. A bit of help @jancborchardt ? :wink:

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice! :)

- What’s this light 1px border around the image?
- I would instead go for: normal, large, and full.
  - normal is the smallest: Used for first run wizard
  - large is the middle one: Used for media files in the viewer
  - full takes the whole width or height, whatever comes first. It also has a full black background and _no_ border-radius. This is how the Gallery looks like right now, and it would be the full focus view when you switch to fullscreen.


------------------------

As said in the polishing issue about the controls:

> - Next & Previous buttons should be further to the sides, to be flush with X exit icon and not take focus away from the content
> - "Next" button shouldn’t be primary blue, takes too much attention from the images

**Comment by skjnldsv** [comment]
> * What’s this light 1px border around the image?

quick mockup issue ;)



> * full takes the whole width or height, whatever comes first. It also has a full black background and _no_ border-radius. This is how the Gallery looks like right now, and it would be the full focus view when you switch to fullscreen.

what about the header?

**Comment by jancborchardt** [comment]
> what about the header?

Just like gallery does it:
- Text has some dark text-shadow for visibility
- Control icons are white and have dark shadow too
- We could even have a short fade in the header from rgba(0,0,0,.3) to transparent, just like Netflix or Youtube does
- The controls fade out anyway

**Comment by skjnldsv** [comment]
Please update review @jancborchardt :hugs: 
dev skjnldsv com_apps_files__dir=_ (1)

**Pull request merged**
