### PR TITLE
Add first vuepress documentation

### LINKED ISSUE #17: Documentation
If possible : automated

### PR DESCRIPTION
**Pull request by juliushaertl**
I gave vuepress a try for building a documentation and this is the first WIP result http://vuecomponents.dev.bitgrid.net/code/components/Avatar/Avatar.html

The big benefit compared to #79 is that we can show actual examples of the component, since vuepress allows integrating components from markdown.

Note: Currently it is required to install vuepress locally, since there seems to be a conflict with the webpack build dependency versions of our repo.

close #17

### CODE REVIEW

**Comment by skjnldsv** [comment]
wow, just wow!! @juliushaertl you're killing it!! :tada: :hugs:

**Comment by skjnldsv** [comment]
@juliushaertl could we get an update on this?
Could be nice since we're getting bigger and bigger here :)

**Comment by juliushaertl** [comment]
Ah yes, I'll have another look so we can get this done.

**Comment by jancborchardt** [comment]
Good stuff, would indeed be great to have direct examples! :) One thing: The avatars are square – is this just because it’s a demo, or an issue in the component? Cause they should be circular. ;)

**Comment by skjnldsv** [comment]
They're square: https://github.com/nextcloud/nextcloud-vue/blob/d3b54578ac7f78c5fff1885e978b758b95a5a8a9/src/components/Avatar/Avatar.vue#L324

Please submit a pr if needed (hiding as off topic both of our messages ;) )

**Comment by skjnldsv** [comment]
@juliushaertl I rebased, but I still cannot get it to work :(

**Comment by juliushaertl** [comment]
Next attempt in #439

**Pull request closed without merging**
