### PR TITLE
chore(release): Bump version to 7.11.4

### PR DESCRIPTION
**Pull request by nickvergessen**
## [v7.11.4](https://github.com/nextcloud/nextcloud-vue/tree/v7.11.4) (2023-05-12)

[Full Changelog](https://github.com/nextcloud/nextcloud-vue/compare/v7.11.3...v7.11.4)

### :rocket: Enhancements

- feat\(NcActions\): Improve readability of action menu entries [\#4049](https://github.com/nextcloud/nextcloud-vue/pull/4049) ([Pytal](https://github.com/Pytal))
- feat\(NcReferencePickerModal\): Allow setting modal size when registering a custom picker component [\#3866](https://github.com/nextcloud/nextcloud-vue/pull/3866) ([julien-nc](https://github.com/julien-nc))

### :bug: Fixed bugs

- fix\(NcListItem\): Fix wrong bold class [\#4083](https://github.com/nextcloud/nextcloud-vue/pull/4083) ([julien-nc](https://github.com/julien-nc))
- fix\(NcSelect\): Fix disabled state of NcSelect with dark mode [\#4079](https://github.com/nextcloud/nextcloud-vue/pull/4079) ([nickvergessen](https://github.com/nickvergessen))
- fix\(NcSelect\): Action input usage [\#4066](https://github.com/nextcloud/nextcloud-vue/pull/4066) ([Pytal](https://github.com/Pytal))

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@nickvergessen rebase

**Comment by GretaD** [comment]
open a new pr with the changelog here: https://github.com/nextcloud/nextcloud-vue/pull/4093 because i rebased this branch wrong locally. Hope this helps :+1:

**Comment by nickvergessen** [comment]
Fixed it and added the changelog manually.
Somehow the github action is unable to detect the non-default-branch target and otherwise listed all the breaking changes from master for 8.0.x

**Review by juliushaertl — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
