### PR TITLE
Bump vue from 2.6.14 to 2.7.8

### PR DESCRIPTION
**Pull request by raimund-schluessler**
This bumps vue to 2.7.8.

This fixes an issue when you use `npm link` with an app that already uses `vue@2.7.8` (e.g. Tasks). Linking then fails with an obscure "vm._scope is undefined" error. Bumping vue here as well makes it work again. Installing nextcloud/vue via npm works in any case.

### CODE REVIEW

**Comment by nickvergessen** [comment]
vue-template-compiler needs to be bumped to the same version?
At least I got errors in some repos otherwise

**Comment by raimund-schluessler** [comment]
> vue-template-compiler needs to be bumped to the same version?
> 
> At least I got errors in some repos otherwise

Yes, it needs to be the same version. I bumped it as well.

**Comment by nickvergessen** [comment]
But package.json in this PR still has `"vue-template-compiler": "^2.6.14",`

**Comment by raimund-schluessler** [comment]
> But package.json in this PR still has `"vue-template-compiler": "^2.6.14",`

Ah, indeed. Here it's listed separately. I was used to the apps were it is required via nextcloud/webpack, so I bumped it via npm update vue-template-compiler.

It could be, that vue-template-compiler is not needed for vue@2.7.8 at all anymore. I will check.

**Comment by raimund-schluessler** [comment]
> But package.json in this PR still has `"vue-template-compiler": "^2.6.14",`

I removed the explicit dependency to vue-template-compiler.

**Comment by juliushaertl** [comment]
The downside of removing the explicit dependency is that dependabot would then not bump those at the same time.

**Review by Pytal — APPROVED** [review]
Other than CI failure and conflicting `package-lock.json`

**Comment by PVince81** [comment]
conflict resolved

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by juliushaertl** [comment]
Marking as breaking as we've seen some incompatibilities when using dependencies that rely on either 2.6 or 2.7 together in text.

**Pull request merged**
