### PR TITLE
Breadcrumb: add exact prop and fix style

### PR DESCRIPTION
**Pull request by skjnldsv**
- Add exact prop for vue router
- Fix styling

| Before | After |
|:---------:|:------:|
|Capture d’écran_2023-01-13_16-31-35|Capture d’écran_2023-01-13_16-31-41|

### CODE REVIEW

**Review by raimund-schluessler — APPROVED** [review]
Seems good, besides the wrong description of the `exact` prop and the two lint warnings.

**Comment by raimund-schluessler** [comment]
Is this component now used somewhere?

**Comment by skjnldsv** [comment]
> Is this component now used somewhere?

Files to vue is in progress :wink: 
But let me edit this PR slightly, I see click is not propagated from the link. We should v-bind and v-on attributes and listeners

**Comment by skjnldsv** [comment]
image

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

**Review by Pytal — APPROVED** [review]

**Pull request merged**
