### PR TITLE
Fix RichEditor rendering of unknown mention, undefined checks and fix default value init

### PR DESCRIPTION
**Pull request by skjnldsv**
- Do not render an unknown mention
- Fix default value if any and fix pasting with custom data

### CODE REVIEW

**Comment by PVince81** [comment]
@skjnldsv test steps to verify ?

**Comment by skjnldsv** [comment]
> @skjnldsv test steps to verify ?

code is pretty straightforward :p
But you can try rendering a mention of a user that is not provided on the userData.
Also see initial value fix:

## Before
Capture d’écran_2020-10-22_09-53-49

## After
Capture d’écran_2020-10-22_09-52-23

**Review by ChristophWurst — APPROVED** [review]
:elephant:

**Comment by skjnldsv** [comment]
Bump!

**Comment by skjnldsv** [comment]
cc @PVince81

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
