### PR TITLE
Drop sidebar position sticky

### LINKED ISSUE #3289: right sidebar moves up and down while resizing the window
Tested on c.nc.com with NC25RC1

When I resize the window the right sidebar (chat) starts to move around.

grafik

Sometimes I can't even access the chat input field.

### PR DESCRIPTION
**Pull request by skjnldsv**
Now that the content is scrolling, the sticky is not needed anymore.
Fixing the top/right values so it can apply on other locations if necessary. Especially the sidebar being full

Fixes this when resizing in firefox
image

Explanations:
Because there is a threesold where sticky positioning takes effect, scrolling makes a weird confusion in firefox where it doesn't understand whether to take the `top: header-height` or not

fix #3289

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Explanation makes sense

**Review by marcoambrosini — APPROVED** [review]
tres bien!

**Review by raimund-schluessler — APPROVED** [review]

**Comment by nickvergessen** [comment]
Screenshots need updates?

**Comment by skjnldsv** [comment]
> Screenshots need updates?

Done

**Comment by skjnldsv** [comment]
Woah, I thought that was merged long ago

**Comment by schiessle** [comment]
Should this be fixed in 25.0.2? Just wonder because I still experience the bug on c.nc.com

**Comment by nickvergessen** [comment]
If it's on talk, it's expected as we did not release yet.

**Comment by nickvergessen** [comment]
In theory yes, but we have another breaking side effect in 7.1 which currently blocks Talk from updating. It is being investigated atm but yeah hopefully in the next Talk version it's fixed

**Pull request merged**
