### PR TITLE
Stop propagation on menu open

### PR DESCRIPTION
**Pull request by skjnldsv**
Before
Peek 18-04-2020 22-01-2

After
Peek 18-04-2020 22-01

### CODE REVIEW

**Comment by skjnldsv** [comment]
@ma12-co I also tried recently to add a click listener on talk so that clicking the message list focus the input, but then clicking the reply or the avatar menu was triggering the click too. This fixes it and will allow to implement this in talk if the talk team wants it

**Comment by raimund-schluessler** [comment]
Hm, I am not sure about this one. Sometimes you want the click to propagate and do someting. In the Calendar app clicking an action e.g. closes the sharing menu, and I think that makes sense. In the Task app e.g. clicking the sort-order dropdown, closes the list renaming input.

I think it is better if the handler that you don't want to be called takes care of detecting where the click came from.

**Comment by korelstar** [comment]
@raimund-schluessler

As far as I can see, this is not about clicking an action item, but clicking the actions three dot menu. I think it's good if that one is handled internally.

**Comment by raimund-schluessler** [comment]
> As far as I can see, this is not about clicking an action item, but clicking the actions three dot menu. I think it's good if that one is handled internally.

Exactly, and I think clicking the three-dot menu should be propagated so other handlers can react to it.

I haven’t tried so far, but wouldn’t this change here also lead to multiple actions menus being open at the same time?

**Comment by korelstar** [comment]
There are still events emitted on open/close, so you are able to react to them if you want:
https://github.com/nextcloud/nextcloud-vue/blob/e22fb09d95f0889869019e3332fd8a07303157d6/src/components/Actions/Actions.vue#L353

**Comment by raimund-schluessler** [comment]
> There are still events emitted on open/close, so you are able to react to them if you want:
> 
> https://github.com/nextcloud/nextcloud-vue/blob/e22fb09d95f0889869019e3332fd8a07303157d6/src/components/Actions/Actions.vue#L353

Doesn’t this only works for parent components?

I will try this PR in an app later today. And let’s hear one other opinion here at least. @georgehrke  @juliushaertl

**Comment by skjnldsv** [comment]
> In the Task app e.g. clicking the sort-order dropdown, closes the list renaming input.

AH, you mean it break the click outside?

**Comment by raimund-schluessler** [comment]
> > In the Task app e.g. clicking the sort-order dropdown, closes the list renaming input.
> 
> AH, you mean it break the click outside?

Yes, it breaks all click-outside-handlers. And you have no way to listen for this click event, since `$emit` only works for parents. So in the Tasks app, the interface looks quite broken now. And it also means, that multiple menus are now open at the same time. This makes no sense in my opinion.

This is how it looks in the Tasks app now. Before, the sharing input, the renaming input and other actions would close when you open another actions dropdown.
stopPropagation

So, I am really against stopping propagation here. It is anyway a bad habit to stop propagation and should be used carefully, https://css-tricks.com/dangers-stopping-event-propagation/. Instead, one can check in the handler that should not be activated where the event came from.

E.g
```
if(!$event.target.closest('.action-item')) return
```
would return early, when the click came from an action. There might be other solutions which don't rely on the CSS class, but it works.

**Comment by skjnldsv** [comment]
> Yes, it breaks all click-outside-handlers. And you have no way to listen for this click event, since `$emit` only works for parents. So in the Tasks app, the interface looks quite broken now. And it also means, that multiple menus are now open at the same time. This makes no sense in my opinion.

right, then it's not something we want :)
This goes against the whole purpose of our Actions click outside :+1:

**Comment by skjnldsv** [comment]
Thanks @raimund-schluessler :)

**Pull request closed without merging**
