### PR TITLE
Webpack config: Remove source-map

### PR DESCRIPTION
**Pull request by marcelklehr**
Fix local styleguide server run

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by marcoambrosini — APPROVED** [review]

**Comment by PVince81** [comment]
so expect devs to manually add the source map back for debugging in browser ?

**Comment by juliushaertl** [comment]
When I checked this it seemed to be mainly caused by outdated dependencies of vue-styleguidedist, namely source-map. Just did a quick test locally and manually installing the latest webpack-sources / source-map package seems to solve the issue:

```
npm install --save-dev source-map
```

Might be nicer to still have the source maps.

**Comment by marcelklehr** [comment]
the npm overrides feature is shipped with npm v8.3+ but also doesn't fix this for me, when pinning all instances in the tree of webpack-sources and source-map to the latest versions. :/ @juliushaertl Can you open a PR with the solution that worked for you, so we can test, perhaps?

**Comment by juliushaertl** [comment]
Now it also seems broken again for me :/ sorry for the false hopes

**Comment by marcoambrosini** [comment]
Aight, I think it's much better to have the docs working than the source maps, at least for me. If no one has time to investigate this further, I'd merge this

**Review by raimund-schluessler — APPROVED** [review]

**Pull request merged**
