### PR TITLE
Use regular text color for selected tag to not de-emphasize

### PR DESCRIPTION
**Pull request by jancborchardt**
Can be tested in Mail with the to, cc and bcc fields @skjnldsv @ChristophWurst   Otherwise there was no difference between placeholder and tag, especially cause there we remove the border.

### CODE REVIEW

**Comment by skjnldsv** [comment]
Please add screeenshot when it's about design! Our design lead is very picky! :D

**Comment by skjnldsv** [comment]
Bump? :wink:

**Comment by jancborchardt** [comment]
@skjnldsv could you review it so we can get it over with? ;) Sorry, appreciate it

**Comment by jancborchardt** [comment]
:bowing_man:

**Pull request merged**
