### PR TITLE
[stable7] revert "fix sidebar scrolling for small displays"

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/nextcloud-vue/issues/3533

Reintroduce https://github.com/nextcloud/server/issues/34777

Signed-off-by: Simon L <szaimen@e.mail.de>

### CODE REVIEW

**Comment by Pytal** [comment]
Guessing this is for `stable7` because `master` is targetting v8 now?

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
There is no stable7 branch.....

**Comment by skjnldsv** [comment]
@Pytal master is still 7.x.x
Please have a look at the milestones, no breaking PR have been merged on master
https://github.com/nextcloud/nextcloud-vue/milestone/85

**Pull request merged**
