### PR TITLE
Fix Modal backdrop

### PR DESCRIPTION
**Pull request by ma12-co**
As discussed in the design group: bring opacity back to .92!

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

**Comment by jancborchardt** [comment]
Also heeeh – I could do it similarly to add a `main-background` prop, so the background is light by default for the Text app? (And icons dark) Seems pretty good, cause I was about to do that quite hackily …

**Comment by ma12-co** [comment]
What do you mean @jancborchardt ? The background is already light by default: https://github.com/nextcloud/nextcloud-vue/blob/323929c2b08bb911419b78b68a96942cbc23bd76/src/components/Modal/Modal.vue#L266
I haven't touched the icons though

**Comment by jancborchardt** [comment]
@ma12-co with "light" I mean "#fff" (that is `var(--color-main-background)`), not "50% transparent black". :)

**Comment by skjnldsv** [comment]
@jancborchardt you should not use the variables here as it will be reverted in dark mode ;)

**Comment by jancborchardt** [comment]
> @jancborchardt you should not use the variables here as it will be reverted in dark mode ;)

The Text app background will also be inverted in dark mode, that’s why I do want to use the variables. :)

**Comment by skjnldsv** [comment]
@jancborchardt then I misunderstood, I thought you were refering to the modal dark bg

**Comment by jancborchardt** [comment]
Just cc'ing @juliushaertl for info when he’s back from vacation cause this is the way we should probably do the Text app background fix so it’s white. :)

**Pull request merged**
