### PR TITLE
Fix sidebar title margins

### PR DESCRIPTION
**Pull request by st3iny**
Fix left margin and add right margin to sidebar title.

## Before

Screenshot 2021-06-22 at 15-54-07 June 2021 - Calendar - Nextcloud

## After

Screenshot 2021-06-22 at 15-53-46 June 2021 - Calendar - Nextcloud

### CODE REVIEW

**Comment by st3iny** [comment]
The cypress baseline has to be adjusted but I don't know how to do that. Any assistance would be appreciated :)

**Comment by raimund-schluessler** [comment]
I am not so fond of this change to be honest (at least the change of the left margin). The reason is that now the title jumps when toggling edit mode, which is something we wanted to prevent iirc:

Before (no jumping):
before

With this change:
after

Maybe we could think about whether we want a left margin only if the input is permanently shown, but not if toggling between title and input is enabled?

**Comment by st3iny** [comment]
I didn't know this was intended behavior.

> Maybe we could think about whether we want a left margin only if the input is permanently shown, but not if toggling between title and input is enabled?

Agreed. In calendar the title is always shown as a form input and the margin doesn't align well with other inputs below.

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Will require upgrade of the regression testing reference images

**Comment by ChristophWurst** [comment]
> Will require upgrade of the regression testing reference images

https://github.com/nextcloud/nextcloud-vue/pull/2055#issuecomment-866008088 :)

**Comment by st3iny** [comment]
I updated all baseline images. CI should be green now.

**Review by skjnldsv — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Pull request merged**
