### PR TITLE
Fix scrolling problem in the menu of boards

### PR DESCRIPTION
**Pull request by lp177**
Allow menu popup to overflow
https://github.com/nextcloud/deck/issues/2104

### CODE REVIEW

**Comment by lp177** [comment]
We can optionnaly for backward compatibility of this choice add an scrollable parameter at true at line 91 and set this two css attributes if true at line 187

**Comment by nickvergessen** [comment]
I think this was fixed with https://github.com/nextcloud/nextcloud-vue/pull/1160 already?

**Comment by lp177** [comment]
Yes that seem to fix also, thanks

**Comment by ma12-co** [comment]
So close this?

**Pull request closed without merging**
