### PR TITLE
Fix actions menu grey focus colour

### PR DESCRIPTION
**Pull request by skjnldsv**
Shadow was a bit too strong and not enough contrasted on dark bg :)

| White | Dark |
|:---------:|:------:|
|Peek 16-05-2019 08-05|Peek 16-05-2019 08-06|

### CODE REVIEW

**Comment by jancborchardt** [comment]
Great great stuff. One thing though, in Mail:
nextcloud mail more menu

Looks a bit strange with the border overlay. I’d even say let’s simply cut the border as the whitespace is enough. Will look much simpler, we already did it in the Android app (both Files app and Notes app) and it’s really nice.

**Comment by skjnldsv** [comment]
@jancborchardt you mean overflow hide?

**Comment by jancborchardt** [comment]
@skjnldsv no, the circle should stay round. :) I simply mean `.app-content-list .app-content-list-item { border-top:none;`:

Current, and then without lines – much simpler and the whitespace is enough to divide (just like we also don’t use divider lines in the app-navigation for example):
contact list current contact list no lines

What do you think?

**Comment by skjnldsv** [comment]
Looks nice :+1: 
I'll try to use it a bit to see if usability is nice as well :)

**Comment by jancborchardt** [comment]
Pull request for core open at https://github.com/nextcloud/server/pull/15691 but kinda needs some fixes in Mail / action menu component as mentioned in there. :)

**Pull request merged**
