### PR TITLE
ListItem Design update

### PR DESCRIPTION
**Pull request by marcoambrosini**
Screenshot 2022-08-17 at 16 20 39

Signed-off-by: Marco Ambrosini <marcoambrosini@icloud.com>

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]
seal

**Comment by jancborchardt** [comment]
Looks very nice! :) 2 questions which are related to ListItem design update:
- Could we shorten the default date format also in the docs so devs use that: https://github.com/nextcloud/mail/pull/6992 (otherwise the date overlaps too much of the title line)
- Shouldn’t the date and unread bubble be hidden on hover, in favor of the 3-dot menu, just like in Talk? Seems a bit much otherwise

**Comment by marcoambrosini** [comment]
> Shouldn’t the date and unread bubble be hidden on hover, in favor of the 3-dot menu, just like in Talk? Seems a bit much otherwise

Yes, by default they are. That second example you see in the docs is a special functionality required by mail in which the visibility of the actions is "forced"

**Review by jancborchardt — APPROVED** [review]
Looks good to me then. :)

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
@marcoambrosini Mind to rebase and resolve the conflict? :)

**Comment by jotoeri** [comment]
Uhh, just saw this effect. Unfortunately, one-line listItems are quite overloaded now. @jancborchardt @marcoambrosini Can we make this optional? So maybe getting the class back, but making the bold-prop default to true?

grafik

**Comment by marcoambrosini** [comment]
this is looking pretty bad in mail's three liners too, so I'd just propose to revert and have them consistent

Screenshot 2022-08-24 at 08 43 42

**Comment by jancborchardt** [comment]
@marcoambrosini fix for that at https://github.com/nextcloud/nextcloud-vue/pull/3136

**Pull request merged**
