### PR TITLE
enh(NcActions): Readability

### PR DESCRIPTION
**Pull request by Pytal**
Before | After
--- | ---
image | image
image | image
image | image
image | image
image | image
image | image
image | image
image | image

### Contrast

> `--color-background-hover` is `#f5f5f5`

`#222222` on `#ffffff` is 15.9:1
`#222222` on `#f5f5f5` is 14.59:1

`#949494` on `#ffffff` is 3.03:1
`#006aa3` on `#f5f5f5` is 5.36:1

### CODE REVIEW

**Review by raimund-schluessler — APPROVED** [review]

**Review by JuliaKirschenheuter — COMMENTED** [review]
Maxcontrast is for borders ok.

Could you please check if background color for actions items is enough with this tool (or some similar tool): https://chrome.google.com/webstore/detail/wcag-color-contrast-check/plnahcmalebffmaghcpcmpaciebdhgdf ? I guess we have to put there higher contrast ratio.

**Comment by nickvergessen** [comment]
I set the milestone to 8 since this goes against master.
If backporting is needed please use the backport bot

**Review by jancborchardt — COMMENTED** [review]
Looks good for the text.
But for the input borders, didn't we introduce a specific lighter color than color-text-maxcontrast there since graphical elements don't need the same contrast amount as text? It is very dark now.

**Comment by nimishavijay** [comment]
> Looks good for the text.
But for the input borders, didn't we introduce a specific lighter color than color-text-maxcontrast there since graphical elements don't need the same contrast amount as text? It is very dark now.

We did, and the minimum color that meets the requirements is also quite dark `#949494`. What we could do is reduce the thickness of the border to 1px (if that is still within the guidelines)

That would result in a lighter looking border

image

**Review by skjnldsv — APPROVED** [review]

**Review by JuliaKirschenheuter — APPROVED** [review]

**Review by nimishavijay — APPROVED** [review]

**Comment by nimishavijay** [comment]
@jancborchardt what do you think about reducing the border thickness to 1px? [screenshots in original comment](https://github.com/nextcloud/nextcloud-vue/pull/4049#issue-1698386225) show how it would look :)

**Pull request merged**
