### PR TITLE
Fix multiselect checkmark and plus icon

### PR DESCRIPTION
**Pull request by skjnldsv**
image

See https://github.com/nextcloud/server/issues/34148

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

**Comment by skjnldsv** [comment]
@szaimen you can do it :)

**Comment by szaimen** [comment]
> @szaimen you can do it :)

I can check tomorrow morning how to do that. Was there some documentation on this somewhere? Also do I have enough permissions to publish the release to npm?

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/nextcloud-vue#releasing-a-pre-release

**Comment by szaimen** [comment]
https://github.com/nextcloud/nextcloud-vue/pull/3515

**Pull request merged**
