### PR TITLE
Fix : Too much space below comment field

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

### CODE REVIEW

**Review by st3iny — COMMENTED** [review]
First of all, thank you for the contribution.

This potentially breaks full height empty contents (e. g. Mail -> right view when no envelope is selected). The icon will be placed at the top rather than floating in the middle.

Maybe we could add a custom selector/prop to make it conditionally float at the top (e. g. `:align="top"` or `:align-top="true"`) of the container. And leave the current behavior as a a default.

**Comment by Jerome-Herbinet** [comment]
> First of all, thank you for the contribution.
> 
> This potentially breaks full height empty contents (e. g. Mail -> right view when no envelope is selected). The icon will be placed at the top rather than floating in the middle.
> 
> Maybe we could add a custom selector/prop to make it conditionally float at the top (e. g. `:align="top"` or `:align-top="true"`) of the container. And leave the current behavior as a a default.

Thanks for your reply. I need somebody to do what you described because I am not very familiar with how "vue" work.
Could you help me ?

**Review by jancborchardt — COMMENTED** [review]
Good improvement design-wise but agree with @st3iny’s feedback. Needs help from Vue experts then. :)

**Comment by marcoambrosini** [comment]
Hi @Jerome-Herbinet!

So basically we need this component to look slightly different depending on where it's used: centered layout and top-aligned layout. For this we can use a prop. Props are one of the ways to pass data to components in Vue. 

the prop declaration within the component would look a bit like:

```
export default {
  props: {
    topAligned: {
        type: Boolean, // the variable type
        default: false, // we don't want to alter the default behavior of the component
}

```

Now a class needs to be added to [the element](https://github.com/nextcloud/nextcloud-vue/blob/de2db0091db0b1ed90313e640aa4412c7d8a34ac/src/components/NcEmptyContent/NcEmptyContent.vue#L78) whenever `top-aligned = true`

this would look like:

```
<div :class="{ 'top-aligned': topAligned}" />
```

And finally create a `top-aligned` class in the css section and do your magic there :) 

We're done with this component, but now you have to go to the parent and pass in `top-aligned = true` as a prop

```
<NcEmptyContent :top-aligned="true" />
```

**Comment by st3iny** [comment]
**PS:** I fixed all usages of `EmptyContent` in the comments app and realized that there already was some code to fix your issue. It just missed an `!important` suffix and thus wasn't applied correctly :see_no_evil: 

I took the liberty to also fix this in my PR.

Ref https://github.com/nextcloud/server/pull/34825

**Comment by Jerome-Herbinet** [comment]
> **PS:** I fixed all usages of `EmptyContent` in the comments app and realized that there already was some code to fix your issue. It just missed an `!important` suffix and thus wasn't applied correctly see_no_evil
> 
> I took the liberty to also fix this in my PR.
> 
> Ref [nextcloud/server#34825](https://github.com/nextcloud/server/pull/34825)

Thanks for your answers @st3iny ; to conclude, should I finally do something on my own with my RP, or should I close it, given your last answer?

**Comment by st3iny** [comment]
I think you can close the PR, now that the issue is fixed.

**Pull request closed without merging**
