### PR TITLE
Actions: Introduce icon slots

### LINKED ISSUE #1270: ActionButton: Add icon slot so material ui icons can be used

### PR DESCRIPTION
**Pull request by marcelklehr**
fixes #1270

### CODE REVIEW

**Comment by skjnldsv** [comment]
I don't think that is the approach we should take.
We should just make an Icon component that can take the aliases we talked about: `material:magnify`

And not allow an entire slot i'd say.

**Comment by marcelklehr** [comment]
> And not allow an entire slot i'd say.

There's already a slot for AppNavigationItems, so I thought this would be consistent, until we figure out a clean way to go forward with icons/logos. Not really particular about this, though. I'm happy to wait until we have good solution.

**Comment by juliushaertl** [comment]
> I don't think that is the approach we should take.
> We should just make an Icon component that can take the aliases we talked about: material:magnify

The issue i see with this is how we would then take care of not bundling all of the icons in the `@nextcloud/vue` library. A slot seems to be the cleanest solution to me where the tree shaking of the icons would be handled by the apps and reduce the implementation effort from the library perspective.

**Comment by skjnldsv** [comment]
> The issue i see with this is how we would then take care of not bundling all of the icons in the `@nextcloud/vue` library. A slot seems to be the cleanest solution to me where the tree shaking of the icons would be handled by the apps and reduce the implementation effort from the library perspective.

Yeah, maybe here it would make sense then.
And only use the said Icon component for our php APIS. :thinking:

**Comment by georgehrke** [comment]
@marcelklehr Is this ready for review? :)

**Review by georgehrke — APPROVED** [review]

**Review by skjnldsv — CHANGES_REQUESTED** [review]
Please add documentation :)

**Review by skjnldsv — APPROVED** [review]

**Pull request merged**
