### PR TITLE
v6.0.0 beta.8

### PR DESCRIPTION
**Pull request by jotoeri**
Still having some hope to use it in production. 😉

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by raimund-schluessler** [comment]
Can someone actually release this to NPM, please?

**Comment by ChristophWurst** [comment]
@GretaD ?

**Comment by jotoeri** [comment]
Maybe also @ChristophWurst, can you try to retrigger the Publish-Action with your permissions? Does the action then run as you or still in my name?

https://github.com/nextcloud/nextcloud-vue/actions/runs/3063047216/jobs/4944696169

**Comment by ChristophWurst** [comment]
:popcorn:

**Comment by ChristophWurst** [comment]
I've recreated the release

**Comment by ChristophWurst** [comment]
Worked.

**Comment by jotoeri** [comment]
Maybe interesting to @skjnldsv:
Retriggering the action by Christoph still recognized me as actor. Maybe with some other Parameter it would recognize Christoph as actor and he could have published by retriggering with just one click. Maybe interesting in General for the actor-permissions-action? 😉 

https://github.com/nextcloud/nextcloud-vue/actions/runs/3063047216

**Pull request merged**
