### PR TITLE
modal-container to overflow: auto

### PR DESCRIPTION
**Pull request by dartcafe**
fix https://github.com/nextcloud/polls/issues/1065

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Still ok on Viewer! :+1:

**Comment by juliushaertl** [comment]
The main issue i see with this is that the rounded corners will no longer be in place when scrollbar is shown:

Chromium:
image

Firefox:
image

Not sure how to solve that properly with the modal size adjusting to the content actually.

**Comment by skjnldsv** [comment]
Ah, there it is. Now I remember why it were there ^^

**Review by ma12-co — COMMENTED** [review]
I would add a div with `overflow: auto` within the modal itself and add a padding in the modal's div. It's what I've been doing in all talk modals.

**Comment by PVince81** [comment]
not sure if related, for the app settings we had to use display: flex to solve scrolling issues, see https://github.com/nextcloud/nextcloud-vue/pull/1573/files#diff-b1113f0551fa6d858b014056d04440a7e6186aabd61fb30c592c11748ee6d463R273

@dartcafe ^

**Comment by szaimen** [comment]
Superseded by https://github.com/nextcloud/nextcloud-vue/pull/2126

**Pull request closed without merging**
