### PR TITLE
increase the small modal width

### PR DESCRIPTION
**Pull request by szaimen**
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by jancborchardt** [comment]
Looks good, but max-width is 100% while max-height is 90% – those should probably be the same, right? Could do 90% (or 95% if needed) on both so it's still a modal-type.

Also @marcoambrosini this is the fix we talked about for the Talk modals. :)

**Comment by szaimen** [comment]
> Looks good, but max-width is 100% while max-height is 90% – those should probably be the same, right? Could do 90% (or 95% if needed)

Not sure about this. I had mobile devices in mind where having as much width as possible is probably desired? But I guess 95% should be fine. What do you think?

**Comment by jancborchardt** [comment]
We do full width/height for the other ones, but for the small size max 95% to have a little bit of modal-ness would be good. :)

**Comment by szaimen** [comment]
> We do full width/height for the other ones, but for the small size max 95% to have a little bit of modal-ness would be good. :)

fine by me then

**Review by jancborchardt — APPROVED** [review]

**Comment by szaimen** [comment]
@marcoambrosini could you give your 👍 if it looks fine to you?

**Review by marcoambrosini — APPROVED** [review]
Looks goood :)

**Pull request merged**
