### PR TITLE
Add trap stack util to public API

### PR DESCRIPTION
**Pull request by Pytal**
For use in server and apps

### CODE REVIEW

**Review by GretaD — APPROVED** [review]

**Comment by skjnldsv** [comment]
Can you describe a location we would use that in server? or app?
Assuming all the elements requiring a focus trap are vue components, doing this should not be necessary

**Review by skjnldsv — CHANGES_REQUESTED** [review]
Can you point or explain a context where we would use that in server or an app?
Assuming all the elements requiring a focus trap are vue components, doing this should not be necessary

**Comment by Pytal** [comment]
> Can you point or explain a context where we would use that in server or an app? Assuming all the elements requiring a focus trap are vue components, doing this should not be necessary

Could be used in https://github.com/nextcloud/server/pull/35381 as the user and contacts menus are not in Vue

**Comment by skjnldsv** [comment]
I would migrate them to vue and use the `HeaderMenu` then, no?

**Comment by Pytal** [comment]
> I would migrate them to vue and use the `HeaderMenu` then, no?

The menus have been using the legacy js implementation for awhile so if the component is flexible enough then sounds good!

Would then need https://github.com/nextcloud/nextcloud-vue/pull/3489 first

**Comment by skjnldsv** [comment]
There was an attempt: 
- https://github.com/nextcloud/server/pull/22274

**Comment by Pytal** [comment]
Not needed as menus will use `NcHeaderMenu`

**Pull request closed without merging**
