### PR TITLE
Make avatar menu focusable with keyboard

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/nextcloud/nextcloud-vue/issues/613

This makes the avatar component focussable with the keyboard and also hitting the enter key will open the menu.
However the menu is not navigable and I'm not sure if we want to reimplement arrow navigation there.

- [x] multiple menus can be open with keyboard as enter doesn't re-close the other menus => solved
- [x] impossible to navigate menu entries with keyboard => tabs

Also, I heard that there will be a revamp of that popover, so the interaction in that popover would be different

### CODE REVIEW

**Comment by PVince81** [comment]
I managed to make this work by automatically setting the focus on the first element inside the menu.
Then it's possible to tab to other menu items. Sadly also possible to leave the popover by tabbing out but there isn't much we can do about this, it's a general, separate issue.

So you can hit enter to open the trigger, then hit enter again on a menu link.

And when the popover is open, if you hit the Escape key, the popover closes and you're back on the trigger. That's near.

Minimal, but neat.

**Comment by PVince81** [comment]
Note: I've developed and tested this with the Talk app and with the participant list on the right of a conversation.

**Review by ma12-co — APPROVED** [review]
tested and works

**Review by GretaD — APPROVED** [review]

**Pull request merged**
