### PR TITLE
Add advanced fields to color picker

### PR DESCRIPTION
**Pull request by Pytal**
Before | After
--- | ---
image | image

<details>
<summary>RGB and HSL</summary>

RGB
image

HSL
image

</details>

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
width looks strange but otherwise good:
image

**Review by marcoambrosini — APPROVED** [review]

**Comment by Pytal** [comment]
Cypress failures unrelated, see https://github.com/nextcloud/nextcloud-vue/issues/3325

**Comment by ChristophWurst** [comment]
FYI as seen in https://github.com/nextcloud/calendar/issues/5013 this change is not backwards compatible for apps that used the old picker

**Comment by raimund-schluessler** [comment]
> FYI as seen in [nextcloud/calendar#5013](https://github.com/nextcloud/calendar/issues/5013) this change is not backwards compatible for apps that used the old picker

I am a bit puzzled. Before this change it wasn't possible to show the advanced fields at all. `:disable-fields="true"` did not offer to show them. Are you sure they were visible?

**Comment by Pytal** [comment]
> I am a bit puzzled. Before this change it wasn't possible to show the advanced fields at all. `:disable-fields="true"` did not offer to show them. Are you sure they were visible?

Precisely, the fields were never visible before and this added them

Seems that the native color picker was used before https://github.com/nextcloud/calendar/commit/e7c489700bcca6d8bacab17585e4437ab7a67afa#diff-cb41e24846d5e15e56c4f885bb5c83fcf872d22c308ef7a529409334bef6c891L81-L88 @ChristophWurst

**Comment by ChristophWurst** [comment]
My bad

**Pull request merged**
