### PR TITLE
Fix menu font for apps

### PR DESCRIPTION
**Pull request by GretaD**
This fixes it for mail

before
accountmenub
after
accountmenu
before
threadmenub
after
threadmenu
before
mailboxmenub
After
mailboxmenu

### CODE REVIEW

**Comment by GretaD** [comment]
this to be merged after this #1542

**Review by skjnldsv — APPROVED** [review]
It's been bothering me for months! ^^'
Yes pleeaaaase ! :rocket: :heart_eyes:

**Comment by PVince81** [comment]
doesn't seem to fix https://github.com/nextcloud/spreed/issues/4330, so the problem for the latter might be elsewhere

**Comment by PVince81** [comment]
not sure why the action buttons in the talk menu would behave differently, it seems that the font size of the "button" is stronger than the one of the "span" that's inside.

I had to move the font-size from the  `&__text` to the parent element to make it work:
```
diff --git a/src/assets/action.scss b/src/assets/action.scss
index 0f5d5e0..6a03eaf 100644
--- a/src/assets/action.scss
+++ b/src/assets/action.scss
@@ -65,6 +65,7 @@
                background-color: transparent;
                box-shadow: none;
 
+               font-size: var(--default-font-size);
                font-weight: normal;
                line-height: $clickable-area;
 
@@ -107,10 +108,6 @@
 
                &__title {
                        font-weight: bold;
-                       font-size: var(--default-font-size);
-               }
-               &__text {
-                       font-size: var(--default-font-size);
                }
        }
 }
```

**Comment by skjnldsv** [comment]
> not sure why the action buttons in the talk menu would behave differently, it seems that the font size of the "button" is stronger than the one of the "span" that's inside.

Maybe this and inherit in the title/text elements?

**Comment by PVince81** [comment]
with the above diff on top of the PR it works for me.

if it also works for mail then we could go with that ?

**Review by PVince81 — APPROVED** [review]
:+1: looks good now also for the Talk menu, thanks

**Pull request merged**
