### PR TITLE
Linkify sidebar title

### PR DESCRIPTION
**Pull request by raimund-schluessler**
Enables linkifying the sidebar title. Partially implement #1090. URLs are now automatically converted to clickable links:

linkify

At the moment it is always enabled. Should we make that configurable with a prop?

### CODE REVIEW

**Comment by skjnldsv** [comment]
I'm not sure about this to be honest. Does it make sense to have links there? :thinking:

**Comment by raimund-schluessler** [comment]
> 
> 
> I'm not sure about this to be honest. Does it make sense to have links there? 🤔

For the Tasks app it absolutely makes sense. It was requested a few times before we implemented it as far as I remember, and I also happen to use it once in a while. It is quite convenient to just paste an URL in the task description which is then automatically rendered as a link, so it can be clicked easily. Otherwise you would need to copy the URL and paste it manually. This would be especially tedious when using #1288, since you would need to go to edit mode first.

But we can sure disable linkifying by default and enable it with a prop.

**Comment by skjnldsv** [comment]
> But we can sure disable linkifying by default and enable it with a prop.

No, let's avoid too much options :p
Let get this in :rocket:

**Comment by nickvergessen** [comment]
We kind of need a way to prevent this.

**Comment by raimund-schluessler** [comment]
With https://github.com/nextcloud/nextcloud-vue/pull/1337 we disabled linkifying by default. You have to enable it with a prop now.

**Pull request merged**
