### PR TITLE
Don't force modal to fill space on mobile

### PR DESCRIPTION
**Pull request by pulsejet**
Don't have a working dev environment for this repo, so didn't test this directly.

@nextcloud/designers 

| Before | After |
| ------------- | ------------- |
| localhost_8035_index php_apps_memories_ (1) | localhost_8035_index php_apps_memories_ |

### CODE REVIEW

**Review by skjnldsv — COMMENTED** [review]
It completely break the purpose of a Modal.
I think [your first screenshot](https://user-images.githubusercontent.com/10709794/237547000-2e1f8c93-e6ea-4b89-897d-b72c0b312ebd.png) is perfectly fine.

If you want to change that, please use dedicated css in your app :)


https://github.com/nextcloud/nextcloud-vue/assets/14975046/f8bd3138-8711-4595-907f-415681eebc08

**Review by skjnldsv — CHANGES_REQUESTED** [review]
See comment

**Comment by skjnldsv** [comment]
PS: if you want o test it live, there is a preview of the documentation on each PR in the github checks list:
image

**Comment by pulsejet** [comment]
Ahh I forgot about the buttons. Makes sense.

> PS: if you want o test it live, there is a preview of the documentation on each PR in the github checks list:

Very cool!

**Pull request closed without merging**
