### PR TITLE
Fix app settings dialog

### PR DESCRIPTION
**Pull request by nickvergessen**
Before | After
---|---
Peek 2022-08-12 13-31 | Peek 2022-08-12 14-36

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
Just for reference, the respective lines were added in https://github.com/nextcloud/nextcloud-vue/pull/2719.

**Review by raimund-schluessler — CHANGES_REQUESTED** [review]
With these changes, scrolling the components content in the docs does not work anymore. Maybe one rather needs to adjust the usage in Talk?

**Comment by nickvergessen** [comment]
The usage in Talk is AppSettingsDialog with tones of AppSettingsSection inside.

Not sure if should be necessary for an app to overwrite overflows of a stand-alone modal component?
https://github.com/nextcloud/spreed/blob/d01450f87a68454a7acf6fa8e51ad8f0bec40ce6/src/components/ConversationSettings/ConversationSettingsDialog.vue

**Comment by raimund-schluessler** [comment]
> The usage in Talk is AppSettingsDialog with tones of AppSettingsSection inside.

Quite the same happens in the docs example, no?

> Not sure if should be necessary for an app to overwrite overflows of a stand-alone modal component? https://github.com/nextcloud/spreed/blob/d01450f87a68454a7acf6fa8e51ad8f0bec40ce6/src/components/ConversationSettings/ConversationSettingsDialog.vue

I guess not. Does it maybe work if you remove the adjustments.

**Comment by nickvergessen** [comment]
The only way I got it working is with these adjustments...

**Comment by raimund-schluessler** [comment]
Really weird. There must be a reason, it works in the docs, but breaks with your changes.

**Comment by raimund-schluessler** [comment]
I cloned and build the Talk app and I couldn't reproduce the scrolling issue in the settings dialog with the Talk master branch. It works just fine (besides #3029).

But I have the assumption that it could depend on how the bundler packed everything together, since this rule
https://github.com/nextcloud/nextcloud-vue/blob/0324a18e33e390e27549cf2c405ed70df2d41161/src/components/AppSettingsDialog/AppSettingsDialog.vue#L362-L365
conflicts with this rule
https://github.com/nextcloud/nextcloud-vue/blob/0324a18e33e390e27549cf2c405ed70df2d41161/src/components/Modal/Modal.vue#L868-L869
and the order of them in the bundle (which might vary) determines which one applies.

So the rule overwriting the style for AppSettingsDialog needs to be more specific. I will create a PR over the weekend.

**Comment by nickvergessen** [comment]
Thanks for diving in as so often recently @raimund-schluessler

**Comment by raimund-schluessler** [comment]
Alternative solution is in https://github.com/nextcloud/nextcloud-vue/pull/3035.

**Comment by raimund-schluessler** [comment]
Closed with https://github.com/nextcloud/nextcloud-vue/pull/3035 and https://github.com/nextcloud/spreed/pull/7745.

**Pull request closed without merging**
