### PR TITLE
v5.1.2

### PR DESCRIPTION
**Pull request by marcoambrosini**
Signed-off-by: marco <marcoambrosini@pm.me>

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Comment by ChristophWurst** [comment]
I see https://github.com/nextcloud/nextcloud-vue/pull/2553 was release in the same fashion and the changelog wasn't complete either. @skjnldsv to the rescue. What should be released off master and what from stable branches? https://github.com/nextcloud/nextcloud-vue#releasing-a-new-version doesn't tell.

**Comment by nickvergessen** [comment]
As far as I understood basically once the first breaking change comes into master we create a stable5 and then it's split

**Review by nickvergessen — APPROVED** [review]

**Comment by ChristophWurst** [comment]
Then this should be a minor, shouldn't it? There are changes other than fixes.

**Comment by marcoambrosini** [comment]
Ok, I'll do a minor and include https://github.com/nextcloud/nextcloud-vue/pull/2566#pullrequestreview-918362444

**Pull request closed without merging**
