### PR TITLE
Do not check l10n comments

### PR DESCRIPTION
**Pull request by skjnldsv**
I'm sure we can survive without them

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:cry:

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
hah, I knew it....

**Comment by PVince81** [comment]
@skjnldsv can you take care (as it was your PR) ? otherwise let me know if I should take over

**Comment by skjnldsv** [comment]
Ah shit, I pushed to stable2

```
10:18 [admin@workstation] ~/git/nextcloud-vue% gcb stable2/backport/1597
fatal: cannot lock ref 'refs/heads/stable2/backport/1597': 'refs/heads/stable2' exists ; unable to create 'refs/heads/stable2/backport/1597'
```

I thought my branch creation was successful --"

**Comment by skjnldsv** [comment]
Well, it's in now I suppose :roll_eyes:

**Comment by PVince81** [comment]
ref https://github.com/nextcloud/nextcloud-vue/commit/afe0613fc5115c55df91fdf82e1cef896afcb571

seems there's a conflict marker, can you solve it ?

**Comment by skjnldsv** [comment]
let me remove the old files yes

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/nextcloud-vue/pull/1598

**Pull request merged**
