### PR TITLE
Fix Content component name to be eslint compliant

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by vinicius73** [comment]
Why not `NCContent`? #2643

**Comment by nickvergessen** [comment]
Because the Button was renamed to ButtonVue, wo I just followed the pattern

**Comment by raimund-schluessler** [comment]
> Why not `NCContent`? #2643

I would also find it sensible to fix it all together with the other component names. An `NC` prefix seems to make sense, but if we apply this to *all*  components it creates a lot of friction when updating to v6 (and changing all component names here). So I am not all set with this solution. `ContentVue` would be in line with e.g. `ButtonVue`, but that anyway was a not really discussed change, so as long as it is consistent, I am good with whatever we chose.

**Comment by raimund-schluessler** [comment]
Input and consensus from @nextcloud/vuejs is required here, I think.

**Comment by skjnldsv** [comment]
If to choose, I would go for NcContent too :)
Note the lowercase `c` because it's `Nextcloud` and not `NextCloud` :see_no_evil:

**Comment by raimund-schluessler** [comment]
Let's do a little poll :laughing: 

- :heart: = `NcContent`
- :rocket: = `ContentVue`

Like and edit my comment if necessary.

**Comment by raimund-schluessler** [comment]
Superseded by #3058.

**Pull request closed without merging**
