### PR TITLE
4.0.1

### PR DESCRIPTION
**Pull request by marcoambrosini**

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
@marcoambrosini I think you manually need to commit the generated change log and force-push it here. Other than that, fine with me.

**Review by skjnldsv — CHANGES_REQUESTED** [review]
https://github.com/nextcloud/nextcloud-vue/pull/2028

**Comment by skjnldsv** [comment]
Please rebase and update changelog :)

**Comment by skjnldsv** [comment]
Changelog 


## [v4.0.1](v4.0.1) (2021-06-14)

[Full Changelog](v4.0.0...v4.0.1 (compare))

## Fixed bugs

- Safely check the global appName and handle its inexistence [\#2028](nextcloud/nextcloud-vue/pull/2028) ([ChristophWurst](@ChristophWurst))
- Do not use app-content-wrapper if no list is provided [\#2026](nextcloud/nextcloud-vue/pull/2026) ([skjnldsv](@skjnldsv))

## Closed pull requests

- Fix settings navigation  layout [\#2033](nextcloud/nextcloud-vue/pull/2033) ([marcoambrosini](@marcoambrosini))
- Set AppNavigation examples' width to 300px [\#2030](nextcloud/nextcloud-vue/pull/2030) ([korelstar](@korelstar))

**Review by skjnldsv — APPROVED** [review]

**Review by GretaD — APPROVED** [review]

**Pull request merged**
