### PR TITLE
Allow custom atrributes to popovermenu entries

### PR DESCRIPTION
**Pull request by skjnldsv**
Allow us to provide custom attributes that will be applied to the element directly:
```js
{
	icon: 'icon-download',
	text: t('contacts', 'Download'),
	href: this.contact.url,
	attr: {
		download: this.contact.displayName + '.vcf'
	}
}
```
```html
<a href="/.../xxx.vcf" rel="noreferrer noopener" download="John doe.vcf">
	<span class="icon-download"></span>
	<span>Download</span>
</a>
```

@nextcloud/vue is this the way to go? Would you prefer individual properties like `item.download` instead?

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> @nextcloud/vue is this the way to go? Would you prefer individual properties like `item.download` instead?

🤷

**Comment by skjnldsv** [comment]
@ChristophWurst because then we could directly remove the properties like`item.href` and put them into attr instead ! :thinking:

**Comment by ChristophWurst** [comment]
We can do that. But tbh I'm not a big fan of the Object-type props we have for many components in this lib. This makes it just super hard to discover the available properties and the validation does also not work out of the box.

Therefore I would vote for an explicit `download` prop.

**Comment by korelstar** [comment]
@skjnldsv  Do you have any other attributes in mind that could benefit from your approach?

**Comment by skjnldsv** [comment]
> Therefore I would vote for an explicit `download` prop.

I agree, it feels weird then.
Let's go for download on `a`

**Comment by skjnldsv** [comment]
> @skjnldsv Do you have any other attributes in mind that could benefit from your approach?

Not that I'm aware of :thinking:

**Pull request closed without merging**
