### PR TITLE
Don't show navigation of settings modal by default

### PR DESCRIPTION
**Pull request by ma12-co**
Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

**Review by jancborchardt — APPROVED** [review]
Thanks!

**Review by GretaD — APPROVED** [review]

**Comment by skjnldsv** [comment]
So all navigation will be hidden by default everywhere?

**Comment by jancborchardt** [comment]
> So all navigation will be hidden by default everywhere?

It’s only the navigation of the settings modal.

**Comment by skjnldsv** [comment]
> > So all navigation will be hidden by default everywhere?
> 
> It’s only the navigation of the settings modal.

GitHub mobile failed me 😅

**Pull request merged**
