### PR TITLE
Add default font and line size

### PR DESCRIPTION
**Pull request by GretaD**
Signed-off-by: GretaD <gretadoci@gmail.com>

### CODE REVIEW

**Review by ma12-co — COMMENTED** [review]
This line height needs to increase too

**Comment by GretaD** [comment]
> This line height needs to increase too

which one? or you mean in general?

**Comment by GretaD** [comment]
> This line height needs to increase too

which one? or you mean in general?

**Comment by skjnldsv** [comment]
@ma12-co those are the same values as server.

**Review by skjnldsv — APPROVED** [review]

**Review by ma12-co — CHANGES_REQUESTED** [review]
https://github.com/nextcloud/nextcloud-vue/pull/1542/files#diff-6fd3d6cda3923d725efadccd864a5de837a5b612a66e46f87272951e619de207R146

There, now that the font size increased to 15, the font size is 1 px bigger than the line height --> not good :)

**Review by ma12-co — APPROVED** [review]

**Comment by skjnldsv** [comment]
Trying to fix the cypress issue...

**Comment by skjnldsv** [comment]
Yeeep, I'm an idiot! :rocket:

**Pull request merged**
