### PR TITLE
Revert webpack output file name

### PR DESCRIPTION
**Pull request by skjnldsv**
I was right to do a beta lol 
https://github.com/nextcloud/nextcloud-vue/pull/3633/files#r1066789921

### CODE REVIEW

**Review by raimund-schluessler — APPROVED** [review]
But there might be another change necessary, see https://github.com/nextcloud/nextcloud-vue/pull/3633/files#r1066802779

**Comment by skjnldsv** [comment]
<table>
<tr>
	<th>Before</th>
	<th>After</th>
<tr>
	<td><code>13:17 [admin@workstation] ~/git/nextcloud-vue% npm run dev                                                                           git:(e5999882)

> @nextcloud/vue@7.3.0 dev
> webpack --node-env development --progress

This build version hash is 78efc74 

assets by path Components/*.js 15.3 MiB
  asset Components/NcActionInput.js 903 KiB [emitted] (name: Components/NcActionInput)
  + 68 assets
assets by path Mixins/*.js 69.6 KiB
  asset Mixins/richEditor.js 53.2 KiB [emitted] (name: Mixins/richEditor)
  + 3 assets
assets by path Directives/*.js 38.5 KiB
  asset Directives/Tooltip.js 27.9 KiB [emitted] (name: Directives/Tooltip)
  + 2 assets
assets by path *.js 5.87 MiB
  asset ncvuecomponents.js 2.94 MiB [emitted] (name: ncvuecomponents)
  asset install.js 2.93 MiB [emitted] (name: install)
assets by path Functions/*.js 19.8 KiB
  asset Functions/usernameToColor.js 11.2 KiB [emitted] (name: Functions/usernameToColor)
  asset Functions/emoji.js 8.55 KiB [emitted] (name: Functions/emoji)
runtime modules 84.6 KiB 395 modules
modules by path ./src/components/ 1.2 MiB 747 modules
modules by path external "vue-material-design-icons/*.vue" 1.31 KiB 32 modules
modules by path external "@nextcloud/ 504 bytes 12 modules
modules by path ./src/utils/*.js 16.6 KiB 11 modules
modules by path ./node_modules/ 21.6 KiB 11 modules
modules by path ./src/mixins/ 33.6 KiB 9 modules
modules by path ./src/directives/ 9.51 KiB 6 modules
modules by path ./src/functions/ 5.67 KiB 5 modules
modules by path ./src/*.js 2.16 KiB 3 modules
modules by path ./src/assets/status-icons/*.svg 1.42 KiB
  ./src/assets/status-icons/user-status-online.svg 394 bytes [built] [code generated]
  + 2 modules
+ 24 modules
webpack 5.75.0 compiled successfully in 5896 ms
</code></td>
	<td><code>
13:15 [admin@workstation] ~/git/nextcloud-vue% npm run dev                                              git:(fix(webpack)-revert-output-file-name*)

> @nextcloud/vue@7.4.0-beta.0 dev
> webpack --node-env development --progress

Building @nextcloud/vue 7.4.0-beta.0 

This build version hash is 1433927 

assets by path Components/*.js 15.7 MiB
  asset Components/NcActionInput.js 922 KiB [emitted] (name: Components/NcActionInput) 1 related asset
  + 70 assets
assets by path Mixins/*.js 72.5 KiB
  asset Mixins/richEditor.js 54.3 KiB [emitted] (name: Mixins/richEditor) 1 related asset
  + 3 assets
assets by path Directives/*.js 39 KiB
  asset Directives/Tooltip.js 28.2 KiB [emitted] (name: Directives/Tooltip) 1 related asset
  + 2 assets
assets by path *.js 6.02 MiB
  asset ncvuecomponents.js 3.02 MiB [emitted] (name: ncvuecomponents) 1 related asset
  asset install.js 3 MiB [emitted] (name: install) 1 related asset
assets by path Functions/*.js 20 KiB
  asset Functions/usernameToColor.js 11.5 KiB [emitted] (name: Functions/usernameToColor) 1 related asset
  asset Functions/emoji.js 8.49 KiB [emitted] (name: Functions/emoji) 1 related asset
runtime modules 91 KiB 446 modules
modules by path ./src/components/ 1.2 MiB 756 modules
modules by path external "vue-material-design-icons/*.vue" 1.31 KiB 32 modules
modules by path ./node_modules/ 23.3 KiB 12 modules
modules by path external "@nextcloud/ 504 bytes 12 modules
modules by path ./src/utils/*.js 16.6 KiB 11 modules
modules by path ./src/mixins/ 34 KiB 9 modules
modules by path ./src/directives/ 9.51 KiB 6 modules
modules by path ./src/functions/ 5.67 KiB 5 modules
modules by path ./src/*.js 2.16 KiB 3 modules
modules by path ./src/assets/status-icons/*.svg 1.42 KiB 3 modules
+ 26 modules
webpack 5.75.0 compiled successfully in 6354 ms
</code>
	</td>
</table>

**Comment by skjnldsv** [comment]
| 7.3.0 | This PR |
|:---------:|:------:|
|image|image|

**Comment by skjnldsv** [comment]
<table>
<tr>
	<th>7.3.0</th>
	<th>This PR</th>
<tr>
	<td>image</td>
	<td>xxxx</td>
<tr>
	<td><code>
dist
├── Components
│   ├── NcActionButton.js
│   ├── NcActionButton.js.map
│   ├── NcActionCaption.js
│   ├── NcActionCaption.js.map
│   ├── NcActionCheckbox.js
│   ├── NcActionCheckbox.js.map
│   ├── NcActionInput.js
│   ├── NcActionInput.js.map
│   ├── NcActionLink.js
│   ├── NcActionLink.js.map
│   ├── NcActionRadio.js
│   ├── NcActionRadio.js.map
│   ├── NcActionRouter.js
│   ├── NcActionRouter.js.map
│   ├── NcActionSeparator.js
│   ├── NcActionSeparator.js.map
│   ├── NcActions.js
│   ├── NcActions.js.map
│   ├── NcActionTextEditable.js
│   ├── NcActionTextEditable.js.map
│   ├── NcActionText.js
│   ├── NcActionText.js.map
│   ├── NcAppContentDetails.js
│   ├── NcAppContentDetails.js.map
│   ├── NcAppContent.js
│   ├── NcAppContent.js.map
│   ├── NcAppContentList.js
│   ├── NcAppContentList.js.map
│   ├── NcAppNavigationCaption.js
│   ├── NcAppNavigationCaption.js.map
│   ├── NcAppNavigationCounter.js
│   ├── NcAppNavigationCounter.js.map
│   ├── NcAppNavigationIconBullet.js
│   ├── NcAppNavigationIconBullet.js.map
│   ├── NcAppNavigationItem.js
│   ├── NcAppNavigationItem.js.map
│   ├── NcAppNavigation.js
│   ├── NcAppNavigation.js.map
│   ├── NcAppNavigationNewItem.js
│   ├── NcAppNavigationNewItem.js.map
│   ├── NcAppNavigationNew.js
│   ├── NcAppNavigationNew.js.map
│   ├── NcAppNavigationSettings.js
│   ├── NcAppNavigationSettings.js.map
│   ├── NcAppNavigationSpacer.js
│   ├── NcAppNavigationSpacer.js.map
│   ├── NcAppNavigationToggle.js
│   ├── NcAppNavigationToggle.js.map
│   ├── NcAppSettingsDialog.js
│   ├── NcAppSettingsDialog.js.map
│   ├── NcAppSettingsSection.js
│   ├── NcAppSettingsSection.js.map
│   ├── NcAppSidebar.js
│   ├── NcAppSidebar.js.map
│   ├── NcAppSidebarTab.js
│   ├── NcAppSidebarTab.js.map
│   ├── NcAvatar.js
│   ├── NcAvatar.js.map
│   ├── NcBreadcrumb.js
│   ├── NcBreadcrumb.js.map
│   ├── NcBreadcrumbs.js
│   ├── NcBreadcrumbs.js.map
│   ├── NcButton.js
│   ├── NcButton.js.map
│   ├── NcCheckboxRadioSwitch.js
│   ├── NcCheckboxRadioSwitch.js.map
│   ├── NcColorPicker.js
│   ├── NcColorPicker.js.map
│   ├── NcContent.js
│   ├── NcContent.js.map
│   ├── NcCounterBubble.js
│   ├── NcCounterBubble.js.map
│   ├── NcDashboardWidgetItem.js
│   ├── NcDashboardWidgetItem.js.map
│   ├── NcDashboardWidget.js
│   ├── NcDashboardWidget.js.map
│   ├── NcDatetimePicker.js
│   ├── NcDatetimePicker.js.map
│   ├── NcDateTimePickerNative.js
│   ├── NcDateTimePickerNative.js.map
│   ├── NcEllipsisedOption.js
│   ├── NcEllipsisedOption.js.map
│   ├── NcEmojiPicker.js
│   ├── NcEmojiPicker.js.map
│   ├── NcEmptyContent.js
│   ├── NcEmptyContent.js.map
│   ├── NcGuestContent.js
│   ├── NcGuestContent.js.map
│   ├── NcHeaderMenu.js
│   ├── NcHeaderMenu.js.map
│   ├── NcHighlight.js
│   ├── NcHighlight.js.map
│   ├── NcIconSvgWrapper.js
│   ├── NcIconSvgWrapper.js.map
│   ├── NcInputField.js
│   ├── NcInputField.js.map
│   ├── NcListItemIcon.js
│   ├── NcListItemIcon.js.map
│   ├── NcListItem.js
│   ├── NcListItem.js.map
│   ├── NcLoadingIcon.js
│   ├── NcLoadingIcon.js.map
│   ├── NcModal.js
│   ├── NcModal.js.map
│   ├── NcMultiselect.js
│   ├── NcMultiselect.js.map
│   ├── NcMultiselectTags.js
│   ├── NcMultiselectTags.js.map
│   ├── NcNoteCard.js
│   ├── NcNoteCard.js.map
│   ├── NcPasswordField.js
│   ├── NcPasswordField.js.map
│   ├── NcPopover.js
│   ├── NcPopover.js.map
│   ├── NcPopoverMenu.js
│   ├── NcPopoverMenu.js.map
│   ├── NcProgressBar.js
│   ├── NcProgressBar.js.map
│   ├── NcRelatedResourcesPanel.js
│   ├── NcRelatedResourcesPanel.js.map
│   ├── NcRichContenteditable.js
│   ├── NcRichContenteditable.js.map
│   ├── NcSavingIndicatorIcon.js
│   ├── NcSavingIndicatorIcon.js.map
│   ├── NcSelect.js
│   ├── NcSelect.js.map
│   ├── NcSelectTags.js
│   ├── NcSelectTags.js.map
│   ├── NcSettingsInputText.js
│   ├── NcSettingsInputText.js.map
│   ├── NcSettingsSection.js
│   ├── NcSettingsSection.js.map
│   ├── NcSettingsSelectGroup.js
│   ├── NcSettingsSelectGroup.js.map
│   ├── NcTextField.js
│   ├── NcTextField.js.map
│   ├── NcTimezonePicker.js
│   ├── NcTimezonePicker.js.map
│   ├── NcUserBubble.js
│   ├── NcUserBubble.js.map
│   ├── NcVNodes.js
│   └── NcVNodes.js.map
├── Directives
│   ├── Focus.js
│   ├── Focus.js.map
│   ├── Linkify.js
│   ├── Linkify.js.map
│   ├── Tooltip.js
│   └── Tooltip.js.map
├── Functions
│   ├── emoji.js
│   ├── emoji.js.map
│   ├── usernameToColor.js
│   └── usernameToColor.js.map
├── install.js
├── install.js.map
├── Mixins
│   ├── excludeClickOutsideClasses.js
│   ├── excludeClickOutsideClasses.js.map
│   ├── isFullscreen.js
│   ├── isFullscreen.js.map
│   ├── isMobile.js
│   ├── isMobile.js.map
│   ├── richEditor.js
│   └── richEditor.js.map
├── ncvuecomponents.js
└── ncvuecomponents.js.map

4 directories, 164 files
</code></td>
	<td><code>
dist
├── Components
│   ├── NcActionButton.js
│   ├── NcActionCaption.js
│   ├── NcActionCheckbox.js
│   ├── NcActionInput.js
│   ├── NcActionLink.js
│   ├── NcActionRadio.js
│   ├── NcActionRouter.js
│   ├── NcActionSeparator.js
│   ├── NcActions.js
│   ├── NcActionTextEditable.js
│   ├── NcActionText.js
│   ├── NcAppContentDetails.js
│   ├── NcAppContent.js
│   ├── NcAppContentList.js
│   ├── NcAppNavigationCaption.js
│   ├── NcAppNavigationCounter.js
│   ├── NcAppNavigationIconBullet.js
│   ├── NcAppNavigationItem.js
│   ├── NcAppNavigation.js
│   ├── NcAppNavigationNewItem.js
│   ├── NcAppNavigationNew.js
│   ├── NcAppNavigationSettings.js
│   ├── NcAppNavigationSpacer.js
│   ├── NcAppNavigationToggle.js
│   ├── NcAppSettingsDialog.js
│   ├── NcAppSettingsSection.js
│   ├── NcAppSidebar.js
│   ├── NcAppSidebarTab.js
│   ├── NcAvatar.js
│   ├── NcBreadcrumb.js
│   ├── NcBreadcrumbs.js
│   ├── NcButton.js
│   ├── NcCheckboxRadioSwitch.js
│   ├── NcColorPicker.js
│   ├── NcContent.js
│   ├── NcCounterBubble.js
│   ├── NcDashboardWidgetItem.js
│   ├── NcDashboardWidget.js
│   ├── NcDatetimePicker.js
│   ├── NcDateTimePickerNative.js
│   ├── NcEllipsisedOption.js
│   ├── NcEmojiPicker.js
│   ├── NcEmptyContent.js
│   ├── NcGuestContent.js
│   ├── NcHeaderMenu.js
│   ├── NcHighlight.js
│   ├── NcInputField.js
│   ├── NcListItemIcon.js
│   ├── NcListItem.js
│   ├── NcLoadingIcon.js
│   ├── NcModal.js
│   ├── NcMultiselect.js
│   ├── NcMultiselectTags.js
│   ├── NcNoteCard.js
│   ├── NcPasswordField.js
│   ├── NcPopover.js
│   ├── NcPopoverMenu.js
│   ├── NcProgressBar.js
│   ├── NcRelatedResourcesPanel.js
│   ├── NcRichContenteditable.js
│   ├── NcSelect.js
│   ├── NcSelectTags.js
│   ├── NcSettingsInputText.js
│   ├── NcSettingsSection.js
│   ├── NcSettingsSelectGroup.js
│   ├── NcTextField.js
│   ├── NcTimezonePicker.js
│   ├── NcUserBubble.js
│   └── NcVNodes.js
├── Directives
│   ├── Focus.js
│   ├── Linkify.js
│   └── Tooltip.js
├── Functions
│   ├── emoji.js
│   └── usernameToColor.js
├── install.js
├── Mixins
│   ├── excludeClickOutsideClasses.js
│   ├── isFullscreen.js
│   ├── isMobile.js
│   └── richEditor.js
└── ncvuecomponents.js

4 directories, 80 files
</code></td>
</table>

**Comment by raimund-schluessler** [comment]
@skjnldsv I think
```js
		config.entry = {
			index: path.join(__dirname, 'src', 'index.js'),
		}
```
is also missing in this block here:
https://github.com/nextcloud/nextcloud-vue/blob/643ccc6d4b4331d7f1987d8cf95c158aba58985b/webpack.config.js#L114-L124

Compare the 7.3.0 version:
https://github.com/nextcloud/nextcloud-vue/blob/e5999882e2ae4fe22b2c72e3671ef509e1e8a36e/webpack.config.js#L159-L161

**Comment by skjnldsv** [comment]
Yeah, but we never build the module in the end, right @raimund-schluessler ?
I mean, we never released that with them :thinking:

**Comment by skjnldsv** [comment]
> Edit: This should explain why `index.module.js` and it's map is missing in the output.

Nah, it's because I ran `npm run dev`

**Comment by skjnldsv** [comment]
Fixed, both 7.3 and this now output 4 directories and 166 files.

**Comment by raimund-schluessler** [comment]
@skjnldsv Thanks for taking care and cleaning up behind me 🙈 😆

**Comment by skjnldsv** [comment]
> @skjnldsv Thanks for taking care and cleaning up behind me see_no_evil laughing

Well, we're all here for each others :hugs: 
Thanks for pushing forward!

**Pull request merged**
