### PR TITLE
Eslint/@nextcloud

### PR DESCRIPTION
**Pull request by skjnldsv**

### CODE REVIEW

**Comment by skjnldsv** [comment]
> Not very related but... Closing bracket on a new line for nicer diffs and clearer structure :D ????

let's not have this discussion again please :sweat_smile: 
https://github.com/nextcloud/eslint-config/pull/1

**Comment by ma12-co** [comment]
> let's not have this discussion again please sweat_smile

I had to try :sweat_smile:

**Comment by ma12-co** [comment]
> nextcloud/eslint-config#8

Oh I wasn't aware of this, I would certainly have lobbied for it :)

**Comment by juliushaertl** [comment]
Hmm, CI is not that happy :wink:

**Comment by skjnldsv** [comment]
> Hmm, CI is not that happy

Yeah, there is some linting fix to finish ;)

**Comment by juliushaertl** [comment]
Ah I was just following the crowd of reviewers and ignoring the `2. developing` :see_no_evil:

**Comment by skjnldsv** [comment]
Should be good to go :)
Lots of `warning  Using exported name 'ActionButton' as identifier for default export             import/no-named-as-default` Maybe we could disable this, I think it's to avoid typos ?

**Comment by skjnldsv** [comment]
@juliushaertl @ChristophWurst any of you know why the l10n action is failing?

**Comment by ChristophWurst** [comment]
> @juliushaertl @ChristophWurst any of you know why the l10n action is failing?

Because you changed source files and thus the line references need an update

**Pull request merged**
