### PR TITLE
Fix/remove margin below message in widget item

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
### ☑️ Resolves

* Fix https://github.com/nextcloud/server/issues/36978
* Fix https://github.com/nextcloud/server/issues/39064

### 🖼️ Screenshots

|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
| image | Screenshot from 2023-06-29 11-04-42
| user status | user status2

### 🏁 Checklist

- [ ] ⛑️ Tests are included or are not applicable
- [ ] 📘 Component documentation has been extended, updated or is not applicable

### CODE REVIEW

**Comment by JuliaKirschenheuter** [comment]
how could i "backport" to stable8 which is not exist yet?

**Comment by JuliaKirschenheuter** [comment]
My commit have `Signed-off-by`. Why DCO is failing?

**Review by artonge — APPROVED** [review]

**Comment by raimund-schluessler** [comment]
> how could i "backport" to stable8 which is not exist yet?

You should send the PR against `master` and then backport to `stable7`. Our just send the same PR to master, now that you have this one here already.

**Review by raimund-schluessler — APPROVED** [review]

**Comment by JuliaKirschenheuter** [comment]
> You should send the PR against `master` and then backport to `stable7`. Our just send the same PR to master, now that you have this one here already.

Thanks Raimund! I would do it like "usual" but can't wait until stable8 will be ready, this will took some time. But will create a second PR against master.

**Pull request merged**
