### PR TITLE
Allow querying for resources with complex item ids

### PR DESCRIPTION
**Pull request by Pytal**
Query for resources with the item id as a query string parameter instead of a URL path segment to allow for complex ids

For https://github.com/nextcloud/related_resources/pull/124

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: hope it won't break backward compat though

**Comment by Pytal** [comment]
> 👍 hope it won't break backward compat though

`related_resources` v1 major for `stable25` will keep the `/related/{providerId}/{itemId}` route, it is only dropped for NC26

**Review by artonge — APPROVED** [review]

**Pull request merged**
