### PR TITLE
Automated styling update from server

### PR DESCRIPTION
**Pull request by nextcloud-command**
Auto-generated update of our locally cached css styling from
 * https://nextcloud.github.io/server/apps/theming/css/default.css
 * https://nextcloud.github.io/server/core/css/server.css
 * https://nextcloud.github.io/server/dist/icons.css

### CODE REVIEW

**Comment by Pytal** [comment]
Weird errors here, look familiar @skjnldsv?

**Comment by skjnldsv** [comment]
> Weird errors here, look familiar @skjnldsv?

Yes, we need to update the visual acceptance data

**Comment by skjnldsv** [comment]
We need to update the replacement rules 
https://github.com/nextcloud/nextcloud-vue/blob/0fb902e2185ea67f61a6288cd21ef8c0bab5f550/.github/workflows/server-styling-update.yml#L19-L22

**Comment by skjnldsv** [comment]
Fixed

**Pull request merged**
