### PR TITLE
Add link support to richcontenteditor and fix various issues

### PR DESCRIPTION
**Pull request by skjnldsv**
- Add link support on rendering
- Make sure we also decode &amp;
- Replaced badly used `value` variable
- Make sure regex are multilines and insensitive

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
Works and does the trick for https://github.com/nextcloud/spreed/issues/4950

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
regression in Safari: https://github.com/nextcloud/spreed/issues/4995

seems this new linkify-url lib doesn't work with Safari
and now wondering why we didn't use linkifyjs instead

**Comment by PVince81** [comment]
fix for the regression, make it use linkifyjs instead: https://github.com/nextcloud/nextcloud-vue/pull/1678

**Pull request merged**
