### PR TITLE
Fix value type for DateTimePickerNative

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/nextcloud-vue/issues/3403

### CODE REVIEW

**Comment by PVince81** [comment]
@szaimen it won't. In that ticket/PR we switched to `Date`. The reason it was broken was because it was wrongly set to use a `String`

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by artonge — COMMENTED** [review]
Need to update the jsDoc of this method: https://github.com/nextcloud/nextcloud-vue/blob/ba7c3a42c5133d495a3a80603874aa6289d2c70a/src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue#L333

**Pull request merged**
