### PR TITLE
Fix counter margin

### LINKED ISSUE #1868: AppNavigation counter have wrong right margin
image

### PR DESCRIPTION
**Pull request by ma12-co**
fix #1868

Bringing back only the counter fix.

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

**Review by raimund-schluessler — CHANGES_REQUESTED** [review]
Actions now miss the right margin:

Screenshot_2021-05-03 Nextcloud Vue Style Guide

**Comment by ma12-co** [comment]
> Actions now miss the right margin

:facepalm: done :sweat_smile:

**Review by raimund-schluessler — APPROVED** [review]
Looks good now.

Screenshot_2021-05-03 Nextcloud Vue Style Guide(1)

**Comment by raimund-schluessler** [comment]
The fix for the Calendar app will still be necessary, but I guess that's inevitable and can be fixed quickly in the Calendar app.

**Review by skjnldsv — APPROVED** [review]

**Review by skjnldsv — CHANGES_REQUESTED** [review]
That's a breaker though, not really a fix

**Comment by skjnldsv** [comment]
If we need to fix something for it to ork in another app, that's not ok. This needs to be backportable to stable3, meeaning there should be no other change needed on the app than bumping `@nextcloud/vue`'s version :)

**Comment by raimund-schluessler** [comment]
> 
> 
> If we need to fix something for it to work in another app, that's not ok.
> This needs to be backportable to `stable3`, meaning there should be no other change needed on the app than bumping `@nextcloud/vue`'s version :)

Technically, yes. But using the counter slot like Tasks and Calendar do it, was never really supported by nextcloud/vue. So I am a bit undecided if we need to account for it.

**Comment by skjnldsv** [comment]
The question is, does it works in any of 3.x.x of nextcloud/vue?
If so I assume following proper semver means we need to have this fixed properly?

**Comment by raimund-schluessler** [comment]
> 
> 
> The question is, does it works in any of 3.x.x of nextcloud/vue?
> If so I assume following proper semver means we need to have this fixed properly?

Yes, it does work in 3.x.x. If we want to not break this usage, we could either try to not introduce this wrapper around the CounterBubble or maybe apply this rule to it: 
```css
.app-navigation-entry__counter-wrapper {
    margin-right: 2px;
    display: flex;
    align-items: center;
    flex: 0 1 auto;
}
```
This should also keep it working, I think (didn't test it yet, can do it only in the evening).

**Comment by skjnldsv** [comment]
Why do we need this wrapper at all btw?
I'm also ok adding the wrapper for 4.x.x but only the margin for 3.x.x @ma12-co :)

**Comment by ma12-co** [comment]
> Why do we need this wrapper at all btw?
To apply the extra margin without using v-deep

**Comment by ma12-co** [comment]
Applyed flex rules to solve calendar issue

Screenshot from 2021-05-06 10-45-04

**Review by skjnldsv — APPROVED** [review]

**Comment by raimund-schluessler** [comment]
I can confirm it now works without adjustments, https://github.com/nextcloud/tasks/pull/1564.

**Pull request merged**
