### PR TITLE
Comment placeholder wording fix

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

### CODE REVIEW

**Comment by Jerome-Herbinet** [comment]
Should fix [#3393](https://github.com/nextcloud/nextcloud-vue/issues/3393)

**Comment by nickvergessen** [comment]
> Uncommited l10n changes. Run `npm run l10n:extract`.
Error: Process completed with exit code 1.

**Comment by szaimen** [comment]
@Jerome-Herbinet can you please run `npm run l10n:extract` in order to fix the test? Thank you! :)

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
