### PR TITLE
v4.1.0

### PR DESCRIPTION
**Pull request by ChristophWurst**

### CODE REVIEW

**Comment by ChristophWurst** [comment]
rebased too often, now the changelog generator got rate limited :facepalm:

**Comment by ChristophWurst** [comment]
I think the changelog generator is a bit bugged when it comes to backport/stable releases. it still includes the (breaking) changes against master. @skjnldsv have you ever had this? Do i now generate the changelog manually?

**Comment by skjnldsv** [comment]
> I think the changelog generator is a bit bugged when it comes to backport/stable releases

Might be, sometimes it outputs a lot more info. A bit of copy/paste is needed :see_no_evil:

**Comment by ChristophWurst** [comment]
> Review has been requested on this pull request. It is not required to merge

what? @skjnldsv is this intentional?

**Pull request merged**
