### PR TITLE
Allow to choose boundariesElement for actions' popover

### PR DESCRIPTION
**Pull request by ma12-co**
Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by juliushaertl — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by georgehrke** [comment]
@ma12-co Does this fix https://github.com/nextcloud/nextcloud-vue/issues/1345 ? :)

**Comment by nickvergessen** [comment]
> Does this fix #1345 ? :)

It allows you do fix it yeah, by specifying the element yourself.

**Comment by georgehrke** [comment]
Well, not really, since you can't set custom props for the actions component for secondary actions:
https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/AppSidebar/AppSidebar.vue#L211

Let me see if adding `.app-sidebar` as a boundary works there.

**Comment by ma12-co** [comment]
> Let me see if adding .app-sidebar as a boundary works there.

It does :)

**Comment by ma12-co** [comment]
But it actually should be an object, not a string :/

**Comment by ma12-co** [comment]
I'm testing now with the dom element body and it seems to work. Seems to be that we were passing in the string "body"

**Comment by ma12-co** [comment]
Can confirm: It works by passing the html body element, without the need of specifying a boundarieselement. I have a problem with the prop validator though. Should I just remove it? 

Screenshot from 2020-08-26 11-03-00

**Comment by georgehrke** [comment]
@ma12-co See https://github.com/Akryum/v-tooltip/blob/fa672f6d6d2004d9cb285ce4551f12c9ca1f6540/src/components/Popover.vue#L114L117

**Pull request merged**
