### PR TITLE
Datepicker dark mode

### PR DESCRIPTION
**Pull request by skjnldsv**
Require https://github.com/nextcloud/server/pull/13403

Created an automated font generation that gets applied to the scss.
That way we don't care about the dark theme, it gets automatically changed with the `color` attribute! :heart_eyes: 

capture d ecran_2019-01-07_13-41-45

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> #### Conflicting files
> `package-lock.json`
> `package.json`
> `src/assets/arrow-left-double.svg`
> `src/assets/arrow-left.svg`
> `src/assets/arrow-right-double.svg`
> `src/assets/arrow-right.svg`
> `src/components/DatetimePicker/DatetimePicker.vue`
> `src/components/DatetimePicker/index.scss`

:see_no_evil:

**Comment by ChristophWurst** [comment]
> #### Conflicting files
> `package-lock.json`

well well well

**Comment by hirschrobert** [comment]
could be related error https://github.com/nextcloud/contacts/commit/e1ec0b4521b640c7fc1fdfa4b136a63d315877b9#r31889831

**Comment by raimund-schluessler** [comment]
> Require nextcloud/server#13403

This means, apps that use the datepicker component require >=NC15, although they would work perfectly fine on NC14 otherwise!?

**Comment by ChristophWurst** [comment]
Reminds me that we should have a clear range of supported server versions in this library.

**Comment by skjnldsv** [comment]
@raimund-schluessler yes! Actually that was always the plan. All of our apps migrations supports min 15 :)

**Comment by raimund-schluessler** [comment]
> @raimund-schluessler yes! Actually that was always the plan. All of our apps migrations supports min 15 :)

Ok, fine with me.

**Pull request merged**
