### PR TITLE
Revert listItem bold title

### PR DESCRIPTION
**Pull request by jotoeri**
As of https://github.com/nextcloud/nextcloud-vue/pull/3055#issuecomment-1225273555, reverting the #3055.

### CODE REVIEW

**Review by raimund-schluessler — DISMISSED** [review]

**Review by juliushaertl — APPROVED** [review]

**Review by marcoambrosini — CHANGES_REQUESTED** [review]
There has been a misunderstanding, I was talking about the border radius in that comment, not the bolding of the title, which looks very good both in mail and talk. 
I suggest that to address the issue in collectives we have 2 separate props:
`boldTitle` that defaults true
`boldSubtitle` that defaults false
Sorry for the confusion

**Comment by jotoeri** [comment]
https://deploy-preview-3110--nextcloud-vue-components.netlify.app/#/Components/NcListItems

**Comment by jotoeri** [comment]
> `boldTitle` that defaults true
> `boldSubtitle` that defaults false

Oups, sorry. Didn't read again before changing.
Now its `bold` and `boldTitle`. I thought a bold Subtitle on its own is probably not very useful? Hope, that's also fine?

**Comment by jancborchardt** [comment]
> I thought a bold Subtitle on its own is probably not very useful?

True indeed – maybe makes sense to only have "boldTitle" and "boldAll"?

**Comment by jotoeri** [comment]
> True indeed – maybe makes sense to only have "boldTitle" and "boldAll"?

I could change that, yes, makes it however a breaking change then?

**Comment by marcoambrosini** [comment]
> Now its bold and boldTitle. I thought a bold Subtitle on its own is probably not very useful? Hope, that's also fine?

Fine, but then let's bold everything when this is true :)

**Comment by jotoeri** [comment]
> Fine, but then let's bold everything when this is true :)

Yes, that's what it does. There also is an example in the docs, but seems like this is broken currently unfortunately. 😢

**Pull request closed without merging**
