### PR TITLE
Fix datepicker design regressions

### PR DESCRIPTION
**Pull request by skjnldsv**
We're back to how it was :rocket: 

Peek 06-04-2020 18-51

image
image
image

### CODE REVIEW

**Comment by skjnldsv** [comment]
> The javascript part looks good
You can test it in the docs ;)
https://deploy-preview-995--nextcloud-vue-components.netlify.com/

**Comment by raimund-schluessler** [comment]
The scrollarea for the minute selection is to long. The scrollbar is not necessary at all, but you can still scroll:

Unbenannt

**Comment by skjnldsv** [comment]
> The scrollarea for the minute selection is to long. The scrollbar is not necessary at all, but you can still scroll:

No this is by design, because the selected one is put on the top so they added a bottomPadding of the height of the picker I guess :)

**Comment by raimund-schluessler** [comment]
> > The scrollarea for the minute selection is to long. The scrollbar is not necessary at all, but you can still scroll:
> 
> No this is by design, because the selected one is put on the top so they added a bottomPadding of the height of the picker I guess :)

Ah, I see. Seems weird at first if you don't get the concept, but it makes sense.

**Comment by raimund-schluessler** [comment]
One small issue, that the button is cut-off:

Untitled

How much it is cut-off depends on the month, I think it's worst for May and doesn't happen at all for Jan.

**Comment by raimund-schluessler** [comment]
Besides https://github.com/nextcloud/nextcloud-vue/pull/995#issuecomment-609982955 it looks fine.

**Comment by skjnldsv** [comment]
> Ah, I see. Seems weird at first if you don't get the concept, but it makes sense.

Yeah, kinda agree :thinking:

**Comment by skjnldsv** [comment]
Fixed week panel too
Capture d’écran_2020-04-07_09-10-18

**Comment by skjnldsv** [comment]
Thanks everyone for helping get this in quick :)
Let me release

**Comment by raimund-schluessler** [comment]
The year button is still cut-off:
Unbenannt

**Pull request merged**
