### PR TITLE
Fix misnamed attribute menu-align

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by nickvergessen** [comment]
The whole UI looks weird now that the seetting is respected again.
Should we maybe not forward it and instead ask apps to use placement if they want it instead, so they can reconsider while touching it?

**Comment by raimund-schluessler** [comment]
I would rather remove the attribute, than make it work. Placement right looks quire weird to me as well, e.g. for `ListItem`:
Screenshot 2022-08-10 at 22-13-22 Nextcloud Vue Style Guide

I think the standard auto works just fine.

**Review by marcoambrosini — APPROVED** [review]

**Comment by marcoambrosini** [comment]
so should we just remove this?

**Comment by raimund-schluessler** [comment]
Superseded by #3749.

**Pull request closed without merging**
