### PR TITLE
Automated styling update from server

### PR DESCRIPTION
**Pull request by nextcloud-command**
Auto-generated update of our locally cached css styling from
 * https://nextcloud.github.io/server/apps/theming/css/default.css
 * https://nextcloud.github.io/server/core/css/server.css
 * https://nextcloud.github.io/server/dist/icons.css

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
@skjnldsv There seems to be something wrong with the automatic fetching. It fetched a HTML error page instead of the CSS files.

**Comment by raimund-schluessler** [comment]
This site https://nextcloud.github.io/server/apps/theming/css/default.css does not exist anymore. Was there a change in server, or is something else wrong?

**Comment by skjnldsv** [comment]
> This site [nextcloud.github.io/server/apps/theming/css/default.css](https://nextcloud.github.io/server/apps/theming/css/default.css) does not exist anymore. Was there a change in server, or is something else wrong?

Weird, let me see

**Comment by skjnldsv** [comment]
Seems new github beta page feature was enabled but not configured. Fallback to the standard deployment method

**Comment by skjnldsv** [comment]
Restarted

**Review by skjnldsv — APPROVED** [review]

**Comment by raimund-schluessler** [comment]
The width of the input fields and, more critically, their font-size has changed. Is this desired?

See this example:
|before|after|
|-|-|
|NcAppSidebar vue-subtitle_null-starred_false-compact_false-header_image-secondary_button-editable_true-base|NcAppSidebar vue-subtitle_null-starred_false-compact_false-header_image-secondary_button-editable_true-actual|

**Comment by skjnldsv** [comment]
> Is this desired?

Nope. Probably a missing property here.
Inputs are supposedly using the variable ` font-size: var(--default-font-size);`
https://github.com/nextcloud/nextcloud-vue/blob/998e78b2f38d6c2991770f08c887d4bd56ff5b4e/styleguide/assets/server.css#L1520

**Pull request closed without merging**
