### PR TITLE
Files : Left panel dropdown improvement for NC 26

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
* Resolves:  [#38155](https://github.com/nextcloud/server/issues/38155)

(from @Clementine46)

**/!\ Testing is welcome in order to make sure it's not doing side effects elsewhere in the UI.**

## Before : 
[before.webm](https://github.com/nextcloud/nextcloud-vue/assets/33763786/653d4208-0dd7-4d4f-a32c-0177ce6988e3)

## After  : 
[after.webm](https://github.com/nextcloud/nextcloud-vue/assets/33763786/d5a919ca-28ce-49ec-9106-28dbccf317e6)

### CODE REVIEW

**Comment by Jerome-Herbinet** [comment]
Also see the other PR for Nextcloud 25 https://github.com/nextcloud/server/pull/38217

**Review by nimishavijay — CHANGES_REQUESTED** [review]
Super nice! I would only suggest that the hover effect doesn't need to use the primary color as we don't use that pattern anywhere else yet, the hover feedback can just be the change in the background color :) other than that it looks great!

**Comment by nimishavijay** [comment]
I meant the hover effect under the dropdown button icon, on hover the icon changes to the primary color.

image

I just checked the other apps, and you are right, nothing has been changed by you. However, it's not intended in the first place. So I suggest on hover we could just have the background color changing, and the color of the icon can remain the same (--color-main-text). What do you think? :)

**Comment by Jerome-Herbinet** [comment]
> I meant the hover effect under the dropdown button icon, on hover the icon changes to the primary color.
> 
> image
> 
> I just checked the other apps, and you are right, nothing has been changed by you. However, it's not intended in the first place. So I suggest on hover we could just have the background color changing, and the color of the icon can remain the same (--color-main-text). What do you think? :)

OK understood @nimishavijay :-) It's done.

**Review by nimishavijay — APPROVED** [review]
If the hover effect has been changed, then it is good to go! nice work! :)

**Review by skjnldsv — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by GretaD** [comment]
this pr breaks mail, and most probably other apps that have an actionmenu on side bar

Screenshot from 2023-05-17 12-14-29

**Comment by Jerome-Herbinet** [comment]
> this pr breaks mail, and most probably other apps that have an actionmenu on side bar
> 
> Screenshot from 2023-05-17 12-14-29

@GretaD, 
Thanks for your feedback. 
IMO it seems complicated to separate behaviour in nextcloud-vue to apply styles only in "Files" context (obviously, I don't find there any specific class or id to target, relative to Files context).
Instead, what do you think about trying to override CSS styles in apps.scss (core) ?
Any other suggestion ? 

@nimishavijay @jancborchardt @juliushaertl

**Comment by szaimen** [comment]
I think this needs to be handled by this component. If both features are used at the same time, it should not coolide but instead be shown next to each other.

**Comment by ChristophWurst** [comment]
Apps are reaching RC state for Nextcloud 27 today. Can this be fixed quickly or should we revert and redo cleanly?

**Comment by Jerome-Herbinet** [comment]
I think things look more delicate and complex than I thought before starting to work on it. 
I propose to close this RP for now (and retry quietly later).
@szaimen @ChristophWurst

**Comment by szaimen** [comment]
Let me try one thing. If that does not work we can revert this change.

**Comment by Jerome-Herbinet** [comment]
Note also that the problem could be the same in https://github.com/nextcloud/server/pull/38338 event if styles are elsewhere.

**Comment by szaimen** [comment]
This fixes the problem in my testing: https://github.com/nextcloud/nextcloud-vue/pull/4134

Let me know if it also for you :)

**Pull request merged**
