### PR TITLE
Add proper margin to the counter

### PR DESCRIPTION
**Pull request by marcoambrosini**
Fixes regression introduced with [93dd3d1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)

Screenshot 2022-09-14 at 10 37 52

Signed-off-by: Marco Ambrosini <marcoambrosini@icloud.com>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by raimund-schluessler — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
🌝

**Comment by nickvergessen** [comment]
Already backported in https://github.com/nextcloud/nextcloud-vue/pull/3251

**Pull request merged**
