### PR TITLE
fix the size of the popper element

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/server/issues/33839

| Before | After |
|---|---|
| image | image |

Signed-off-by: Simon L <szaimen@e.mail.de>

### CODE REVIEW

**Comment by juliushaertl** [comment]
I think the 50vh approach might also not work well if the header is larger (e.g. with a preview). Maybe we can change the popper positioning strategy so that the popover is not limited to the tab area but may also span over the full window height and be positioned to the left of the button?

**Comment by juliushaertl** [comment]
> Is there no way for the popper element to automatically detect out-of-bound window ?

Might not work in a generic way, so maybe that is something that needs rather some fine tuning in the sharing sidebar implementation.

**Comment by szaimen** [comment]
> I think the 50vh approach might also not work well if the header is larger (e.g. with a preview)

No, that is no problem as it will overlap the preview header then. Let me test this out as well...

**Comment by szaimen** [comment]
@skjnldsv @juliushaertl both edge cases seem to work:
image

**Comment by szaimen** [comment]
@skjnldsv @juliushaertl can you approve? :)

**Review by Pytal — APPROVED** [review]

**Comment by szaimen** [comment]
One additional review needed :)

**Review by PVince81 — APPROVED** [review]
:+1: nice

**Pull request merged**
