### PR TITLE
fix aria-controls

### LINKED ISSUE #950: Actions aria not compliant
Because [we now use v-if for the actions](https://github.com/nextcloud/nextcloud-vue/pull/569), we became non-compliant because the menu containing the id doesn't exist on the page.

image

image

@nextcloud/accessibility

### PR DESCRIPTION
**Pull request by korelstar**
fixes  #950

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
This PR breaks opening the actions menu.

**Comment by raimund-schluessler** [comment]
Reverting https://github.com/nextcloud/nextcloud-vue/pull/951/files#diff-2bfd37a0e52db490178eb64c7675ecc9R93 fixes it. No idea why, though.

**Comment by raimund-schluessler** [comment]
As per https://github.com/nextcloud/nextcloud-vue/pull/952#issuecomment-605412886

> Yeah, we cannot have a vif on slot 🙈
> `<template v-if="opened"><slot /></template>`

But also, I think the `v-click-outside="closeMenu"` immediately closes the menu again (which wasn't the case before, since the element was not in the DOM due to `v-if`.

**Comment by skjnldsv** [comment]
add some debug logs and see?

**Comment by raimund-schluessler** [comment]
> add some debug logs and see?

Yeah, I checked it. That’s the reason.

**Comment by skjnldsv** [comment]
Awesome :)

**Pull request merged**
