### PR TITLE
Trigger value save on year/month select

### LINKED ISSUE #137: Datepicker fixes
- [x] Days of the week should have same colour as disabled days
- [x] More padding on the headers
- [x] Arrows with the same design as the original datepicker
- [ ] OK button with better wording
- [x] Wrap it
- [ ] Automatically use the provider locale from nc

### PR DESCRIPTION
**Pull request by skjnldsv**
See https://github.com/nextcloud/nextcloud-vue/issues/137#issuecomment-481667668
Closes #137

@nextcloud/vue

### CODE REVIEW

**Comment by skjnldsv** [comment]
:trumpet:

**Comment by skjnldsv** [comment]
@caugner this actually caused an issue: https://github.com/nextcloud/contacts/issues/1196

Is this needed when you don't use confirm?
In contacts we do use confirm and this pull request actually introduced the bahaviour you described here: https://github.com/mengxiong10/vue2-datepicker/issues/290#issue-430170187

Now in contacts if you click the year in the header, then select a year, then a month and another date, the year is back to what it previously were.

**Comment by caugner** [comment]
@skjnldsv I have passed the question on to the author of vue2-datepicker: https://github.com/mengxiong10/vue2-datepicker/issues/290#issuecomment-518676347

**Comment by caugner** [comment]
@skjnldsv The vue2-datepicker [has provided](https://github.com/mengxiong10/vue2-datepicker/issues/290#issuecomment-518929676) the following fix:

```js
    handleSelectYear(year) {
      let value = this.$refs.datepicker.currentValue;
      if (value) {
        value = new Date(new Date(value).setFullYear(year));
        this.$refs.datepicker.selectDate(value);
      }
    },
    handleSelectMonth(month) {
      let value = this.$refs.datepicker.currentValue;
      if (value) {
        value = new Date(new Date(value).setMonth(month));
        this.$refs.datepicker.selectDate(value);
      }
    }
```

**Pull request merged**
