### PR TITLE
Don't throw error when getCurrentUser() returns null

### PR DESCRIPTION
**Pull request by raimund-schluessler**
See https://github.com/nextcloud/nextcloud-vue/pull/1030#discussion_r411329088

### CODE REVIEW

**Comment by skjnldsv** [comment]
Hum, there is a dedicated babel plugin for it https://babeljs.io/docs/en/next/babel-plugin-proposal-optional-chaining.html
Are we sure it's already in babel/preset-env?

**Comment by raimund-schluessler** [comment]
I don’t know, I thought the compiler would complain if it doesn’t know it.

**Comment by raimund-schluessler** [comment]
> 
> 
> Hum, there is a dedicated babel plugin for it https://babeljs.io/docs/en/next/babel-plugin-proposal-optional-chaining.html
> Are we sure it's already in babel/preset-env?

It is in babel/preset-env since 7.8.0: https://babeljs.io/blog/2020/01/11/7.8.0

> Babel 7.8.0 supports the new ECMAScript 2020 features by default: you don't need to enable individual plugins for nullish coalescing (??), optional chaining (?.) and dynamic import() anymore with preset-env.

**Comment by raimund-schluessler** [comment]
Is there a reason, why we still require `"@babel/preset-env": "^7.3.1",` in https://github.com/nextcloud/nextcloud-vue/blob/master/package.json#L59?

**Pull request merged**
