### PR TITLE
Bump version to 7.1.0

### PR DESCRIPTION
**Pull request by ChristophWurst**
The last major was v7.0.0 and I see there is a `stable7`, so I assume `master` changes are going to be released as either 7.1 or 8.0 depending on whether we have breaking changes.

### CODE REVIEW

**Comment by mejo-** [comment]
> Who created the stable7 branch?

That was me, after discussion in the fontenders room. But I'm a naive novice :grimacing: So I'm totally fine with removing the branch and continuing 7.0 development in master.

**Comment by skjnldsv** [comment]
Well, no worries, just wondering if there is a underlying motive  :stuck_out_tongue_closed_eyes: 

We never did that in this repo. I am much more in favour of keeping this one as 7.x.x until 8.x.x as usual.
Otherwise it's just duplicating all the mess with backports etc etc

**Comment by ChristophWurst** [comment]
Okay but while we are here, what if we bump to 7.1 and release this shiny new component https://github.com/nextcloud/nextcloud-vue/pull/3369?

**Comment by mejo-** [comment]
> I am much more in favour of keeping this one as 7.x.x until 8.x.x as usual.
> Otherwise it's just duplicating all the mess with backports etc etc

Yep, let's do that. Unfortunately I lack the permissions to delete the protected branch `stable7`, so could someone with super powers do that?

**Comment by ChristophWurst** [comment]
Okay then we don't release the component.

**Comment by skjnldsv** [comment]
@ChristophWurst we will, we just never preemptively bumped versions on master before releasing.
Anyway, 7.1.0 it is! :rocket:

**Pull request closed without merging**
