### PR TITLE
Cleanup avatar fetching methods

### PR DESCRIPTION
**Pull request by skjnldsv**
Pretty much does the same, just a code cleanup!

### CODE REVIEW

**Comment by PVince81** [comment]
will clash with https://github.com/nextcloud/nextcloud-vue/pull/1457 :-/

**Comment by PVince81** [comment]
needs rebase. thanks for approving the other one first :bow:

**Comment by skjnldsv** [comment]
Done

**Review by GretaD — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
code looks fine, still works :+1:

**Pull request merged**
